# Foreign policy, national defense guiding documents

Minister for Ministry of Foregin Affairs, Mr. Pradeep Kuman Gyawali, unveiled Nepal's Foreign Policy document on Dec 6, 2019. The policy aims to secure the country's national interests by deepening mutual cooperation with all friendly countries. The policy paper is also a proper culmination to efforts by various task forces that were formed to upbringing an unified foreign policy at different times.

Although matters relating to the foreign policy conduct were expressed in one way or the other in country's various policy documents, including constitution, national security policy, annual budget and prime ministerial speeches, there had been longstanding lack of a integrated foreign policy document.

The policy also reiterates Nepal's long-standing policy of not allowing its soil to be used against neighboring countries and other countries, while expecting similar cooperation and commitment from them.

## Features of Foreign Policy, 2077

- The country will conduct its independent and balanced ties with neighboring countries based on the principles of the UN Charter, Panchsheel, and good neighborliness.
- Nepal will expand and enhance its ties with neighboring and other friendly countries based on sovereignty equality, mutual respect and benefit, read the policy.
- Nepal's border will be kept intact by protecting international border points. 
- Boundary issues will be resolved through peaceful diplomatic means and dialogue based on treaties, agreements, historic documents, evidence and facts.
- 
