# State, head of the state, ministry and state obligations

## State

Under international law, a State is a legal person with legal rights and obligations. As such a legal person the State is to be distinguished from other corporate entities, whether established by internal law such as a commercial multinational company, or by international law such as an international organization.

the status of a State is not conferred by national laws, although the constitutional law of its own internal national legal system may allocate and determine the manner of the executive, judicial, and legislative powers which it exercises. Its status is based on the exercise of effective control over a population within a defined territory which has been recognized and given effect in international law; and it is international law which determines its capacity as a legal person, its competence, and the nature and the extent of certain rights and duties. These attributes of States distinguish them from international organizations which, although also enjoying legal personality under international law, have no population or territory, and derive their legal personality and power in international law from treaty and the function which the particular organization is created to perform.

### Privileges and immunities of the state

In 1972 the Council of Europe adopted the 1972 European Convention on State Immunity setting out a list of exceptions (including the State’s waiver) to state immunity and this was followed by the enactment in the United States (1976), UK (1978), and in a number of other States of national legislation introducing a range of exceptions to state immunity for commercial transactions and proceedings for personal injuries caused in the territory of the State where the claim was brought. In 2004 the United Nations General Assembly adopted the Convention on the Jurisdictional Immunities of States and their Property. The Convention requires 30 ratifications to bring it into force but, based largely on state practice, as determined by the work of the International Law Commission and 10 years’ discussions in the UN General Assembly’s Sixth (Legal) Committee, it consolidates the restrictive approach to state immunity. By this approach no immunity is afforded in respect of proceedings brought against a State in national courts in respect of commercial transactions or claims for personal injury or tangible loss caused by act of the State within the territory of the State where proceedings are brought, and, as regards measures of execution, limited enforcement of judgments against the State is permitted in respect of state property in commercial use.

## Ministry of Foreign Affairs

The miniser of foreign affairs is the regular but far from exclusive intermediary between the State and foreign countries; his functions are regulated by domestic legislation and traditions, and his powers vary according to the political organizations of different States. In international law the minister for foreign affairs is deemed to have the capacity to represent, to make treaties, and generally to act for the State. Ministers for foreign affairs, together with heads of state and heads of government, are recognized by the Vienna Convention on Treaties 1969, 'in virtue of their functions and without having to produce Full Powers considered as representing their State for the purposes of performing all acts relating to a treaty' (Article 7(2)).

In contemporary Britain the mode of appointment of Her Majesty’s Secretary of State for Foreign and Commonwealth Affairs is by the delivery to him by the Sovereign of the seals of office. There are three seals, viz. a greater and lesser signet and a small seal called the cachet; all of these are engraved with the Royal Arms. The two former now differ only in point of size. In the Foreign and Commonwealth Office, diplomatic and consular commissions signed by the Sovereign pass under the greater signet; the lesser is used in the case of royal exequaturs granted to foreign consular officers, and for royal warrants (such as instruments authorizing the affixing of the Great Seal to Full Powers and to ratifications of treaties); the cachet, now very rarely deployed, is used to seal the envelopes of letters containing communications of a personal character made by the Queen to foreign sovereigns.

Patents were issued from the fifteenth century onwards till 1852. From that time the practice was intermittent till 1868, but since the latter date patents have not been issued, nor in any case would they affect the powers of the Secretary of State for these follow the seals. The British Foreign and Commonwealth Secretary holds a full power from the Queen, authorizing him to negotiate and conclude, subject if necessary to Her Majesty’s ratification, any treaty in respect of Great Britain and Northern Ireland.

Today governments of other countries address themselves to the minister for foreign affairs either through their own accredited diplomatic agent, or through the diplomatic agent who represents his sovereign or government at their own capital. The former is the normal channel of communication and is generally preferred, since by instructing their own representative a government can be confident that the wording and manner of delivery of their message conforms as exactly as possible to their intentions. Moreover, he will report immediately, if necessary, on the reception it obtained. However, there are occasions when a minister for foreign affairs, wishing to communicate his government’s message with the greatest force, will summon a foreign ambassador to receive it personally. In such cases the government’s own representative will of course be informed and may be required to take complementary action in the capital where he is accredited. These procedures are flexible, and the choice will depend upon circumstances and upon the personalities involved.

As a general rule Notes and other formal communications concerning relations with other countries are signed by the minister for foreign affairs or, more frequently, on his behalf. Under his general supervision are drawn up documents connected with foreign relations, drafts of treaties and conventions, statements of fact and law, manifestos, and declarations. The negotiation of treaties rests with him and he watches over their execution. Ratifications of treaties are exchanged by him or his agents. He proposes to the head of state the nomination of diplomatic agents, he is responsible for drawing up their credentials and Full Powers for signature by the head of state, and for the issue of their instructions. He advises the head of state as to the acceptance of persons who have been proposed to be accredited to him, and also as regards the issue of exequaturs to foreign consular officers. Such officers receive their orders from him. Foreign representatives address themselves to him in order to obtain an audience of the head of state.

At the present day the duties and responsibilities of the minister who is entrusted with the conduct of the foreign relations of his country range over a far wider field. The birth of new States, the advancement of others, constitutional changes which may occur in their methods of government, the growth of organizations designed to foster a better understanding between the nations of the world, the ever-increasing complexity of international relationships, and the many questions to which all these give rise, have largely extended the area within which diplomacy finds its proper scope, and call for close and unremitting attention.

On taking office the minister for foreign affairs informs the diplomatic representatives of foreign States of his appointment, and customarily receives them as soon as possible thereafter at his official residence to exchange greetings with them. He also informs the diplomatic agents of his own country accredited abroad.

In every country the foreign minister is assisted by a trained staff that, under his guidance, constitute the foreign office or ministry for foreign affairs. In Nepal, the permanent staff of the Ministry of Foreign Affairs has at its head the Foreign Secretary (currently served by Mr. Bharat Paudyal as of Jan, 2021), who has the rank of ambassador.

### Roles, responsibility, and functions

According to Government of Nepal (Allocation of Business) Rules, 2069 (2012) Ministry of Foreign Affairs has the following roles, responsibility, and function:

- Formulation, implementation, monitoring and evaluation of foreign policy, plan and programs of Nepal
- Relation with foreign nations
- Representation of Nepal in foreign countries
- Publicity of Nepal in foreign countries
- Passport and visa to be issued in abroad
- Hospitality Management
- Protocol
- Claim over a person of a Nepali or foreign citizen by the respective governments.
- Diplomatic protection (immunities) and privileges
- Record of Nepali citizens who are in abroad and their right, interest and protection.
- Non-resident Nepalese
- Economic diplomacy
- Development and promotion of public and non-governmental organizations at international level
- Consular practice
- United Nations, South Asian Association of Regional Cooperation and other international and regional organization
- Foreign diplomatic mission in Nepal
- Negotiation and agreement at diplomatic level (on the matters which do not fall under any other ministry)
- Operation of Nepal foreign service

### Organizational structure

There are two departments under the Ministry of Foreign Affairs:

- Department of Passport (Nepal), Narayanhiti, Kathmandu
- Department of Consular Services, Tripureshwor, Kathmandu

The Ministry has operated a Liaison Office in the border town of Birgunj since 2005.

The Ministry operates the Institute of Foreign Affairs (IFA) in Tripureshwor, Kathmandu.
