# Diplomatic missions and Diplomatic relations of Nepal

## Diplomatic missions

Under long established principles of international law now codified in Article 2 of the Vienna Convention on Diplomatic Relations, the establishment of diplomatic relations between States and the establishment of permanent diplomatic missions take place by mutual consent. The right to send and receive diplomatic agents flows from recognition as a sovereign State and was formerly known as the right of legation (ius legationis).

It is in modern practice highly exceptional for two States to recognize each other without formally establishing diplomatic relations—and such a situation usually indicates extreme tension or coolness between them. The United Kingdom for example recognized North Korea as a State some years before the establishment of diplomatic relations between the two in December 2000.

It is common, though not universal practice, for the government of a State to issue a formal statement on recognizing another-usually newly established-State and such a statement may offer to establish diplomatic relations with the new State, or be followed very shortly by such an offer.

Where the birth of the new State takes place without the consent of the State from whose territory it is being formed, premature recognition and establishment of diplomatic relations by other States will be regarded by the parent State as unlawful and in some circumstances as an intervention in its own internal affairs. Thus in February 1991 the Soviet Union protested at a decision by Iceland to recognize Lithuania-then still regarded by Moscow as a constituent Republic of the USSR-and to establish diplomatic relations with it.

The disappearance of a sovereign State - usually on fusion with another State - is on the same principles followed by the ending of its separate diplomatic relations with other States as they recognize the new situation. On the reunification of Germany in 1989, the separate East German embassies were taken over by the newly reunited Germany. Other States, if they retain former embassy premises in a city which is no longer the seat of government, may transform them into consulates - or perhaps seek the permission of the government of the newly unified State for their transformation into offices forming part of the mission to that State.

Where a change of government within a State takes place, continuance or otherwise of diplomatic relations between that State and others also depends on whether the new government has been recognized. When the change of government is constitutional, for example as a result of free elections, diplomatic relations with other States will continue as a matter of course. Fresh credentials may be required by ambassadors from other States where the new government results from or entails a different head of state. Where a change of government results from conflict or revolution, diplomatic relations may continue or there may be a hiatus, and the appointment of new ambassadors is likely.

Where a government - even one apparently in control of a State - has not received recognition from other States it will be unable to establish or to continue diplomatic relations with these other States and its envoys will not be received abroad, accorded any diplomatic status, or given control of the financial assets or property such as embassy premises belonging to the State.

A State establishes a permanent diplomatic mission in another State with which it is in diplomatic relations only where it decides, first, that a permanent mission is necessary for the conduct on its behalf of some or all of the diplomatic functions described below, and secondly, that conditions in the receiving State would permit its representatives to exercise such functions safely and effectively. Embassies are financed from the resources of the sending State which are in most cases subject to stringent controls and in some cases to public and parliamentary scrutiny of expenditure. So a sending State which has limited political or commercial interests in another State, and few of its own nationals resident in or visiting that State, may well decide that it does not require a permanent embassy there. Where the receiving State is in the midst of armed conflict, civil disorder, or a high level of terrorist threat, other States will in general not set up permanent missions and may withdraw missions already in existence.

In such situations there is a range of more limited options available to the two states for the conduct of their relations:

1. diplomatic contacts in the capital of a third State or in the margins of international organizations - in particular the United Nations;
2. occasional special missions sent to discuss specific issues of mutual interest;
3. multiple accreditation - more usually the sending of a single ambassador to two or more receiving States but less frequently the sending by two or more States of a single ambassador to one receiving State.
4. protection of the interests of the sending State by a third State which is represented in the receiving State.
5. consular relations may be continued or established between the two States in the absence of a permanent diplomatic mission and even in the absence of recognition of the receiving government or of diplomatic relations.


### Functions

The functions of a diplomatic mission, which are set out in Article 3 of the Vienna Convention on Diplomatic Relations, are to represent the sending State, to protect its interests and those of its nationals, to negotiate with the government of the receiving State, to report to the government of the sending State on all matters of importance to it, and to promote friendly relations in general between the two States. 

The mission must seek to develop relations between the two countries in economic, financial, labour, cultural, scientific, and defence matters. Although there have been important changes in the ways in which diplomatic relations are conducted - many due to developments in communications and travel - the basic functions themselves have hardly altered over the past three hundred years. The list in Article 3 is however not exclusive, so that novel forms of cooperation, such as police or judicial liaison over extradition, possible drug trafficking, or child abduction, may be accepted as properly diplomatic in character.

In carrying out all of its functions the mission acts on the instructions received from the government of the sending State and on its behalf. The function of 'representing the sending State' is listed first because it describes not merely ceremonial appearances and acts by an ambassador but embraces all of the subsequently named functions.

A diplomatic mission is required to carry out all of its functions in accordance with international law and also (except where it benefits from a specific exemption) in accordance with the laws and regulations of the receiving State, as dictated by Article 3 of the Vienna Convention. The balancing of the right of an embassy to protect the interests of its own nationals and, more generally, human rights, and its duty not to interfere in the internal affairs of the host State has in recent years given rise to numerous diplomatic disputes, particularly, though not exclusively, in countries which strictly limit freedom of speech and assembly.

## Diplomatic privilage and immunites

The traditional norm of privileged positions of diplomats is necessary because the representatives of a state can only carry out their diplomatic functions satisfactorily if they are utterly free from pressures, whether legal, physical or moral, that the state in which they are serving may be able to impose on them.

Privileges and immunities are applicable both to the diplomatic mission and its functions, and to the individual. Vienna Convention on Diplomatic Relations is widely accepted with reference to provisioning of diplomatic privileges.

**Privileges and immunities in respect of the mission and its function**

1. Inviolability and immunity for premises and property
2. Inviolability of records, documents, correspondence and archieves
3. Freedom and inviolability of communications
4. The diplomatic bag, pouch or valise (sealed bag or container clearly marked as such, containing only official documents and articles for official use)
5. Exemption from taxation
6. Right to import, and exemption from customs duties

**Personal privileges and immunities**

General provisions for personal privileges and immunities are described into two heads based on the extent of coverage:

A. Full diplomatic privileges and immunities applicable to diplomats and member of their families forming part of their household;

1. Immunity from criminal jurisdiction
2. Immunity from civil and administrative jurisdiction
3. Provision of waiver of diplomatic immunity only by their government
4. Counterclaims
5. Inviolability of correspondence
6. Inviolability of property
7. Exemption from liability for public service
8. Exemption from liability to serve as witness
9. Exemption from national and local taxation
10. Exemption from custom duties
11. Exemption from social security provisions
12. Exemption from inspection of personal luggage
13. Freedom of travel

2. Limited diplomatic privileges and immunities.

These privilate are granted to:

1. Non-diplomatic staff of a mission who are not nationals or permanent residents of the state in which they are serving. This class includes members of the administrative and technical staff of a mission; members of their families forming part of their household and members of the domestic ('service') staff of a mission who are not nationals or permanent residents of the state in which they are serving; and private servants of members of the diplomatic staff who are not nationals or permanent residents of the state in which they are serving.
2. Diplomats and other members of the staff of a mission who are nationals or permanent residents of the host state

## Diplomatic mission of Nepal

```{r diplomatic-ties-nepal}
diplomatic_relations <- read_csv("./data/nepal_diplomatic_relations.csv")

diplomatic_relations <- diplomatic_relations %>% 
  mutate(group_id = as.numeric(cut(SN, breaks = 4))) %>% 
  # relocate(row_id, .before = 1) %>% 
  group_split(group_id, .keep = FALSE)

max_rows <- max(map_dbl(diplomatic_relations, nrow))
equalizing_mask <- map_dbl(diplomatic_relations, nrow) != max_rows

diplomatic_relations[equalizing_mask] <- diplomatic_relations[equalizing_mask] %>% 
  map(~add_row(.x, tibble(SN = rep(NA, max_rows-nrow(.x)))))

diplomatic_relations %>% 
  bind_cols() %>% 
  knitr::kable(booktabs = TRUE, col.names = rep(c("SN", "Country", "Date since"), times = 4), caption = "Countries to which Nepal formed diplomatic relation, and the date of first making of such arrangement.", longtable = TRUE) %>% 
  kableExtra::kable_styling(font_size = 6, latex_options = "striped") %>% 
  kableExtra::column_spec(column = 1:12, width = rep(c("0.8em", "6.5em", "6em"), times = 4))
```

## India-Nepal relations

The Republic of India and the Federal Democratic Republic of Nepal initiated their relationship with the 1950 Indo-Nepal Treaty of Peace and Friendship and accompanying secret letters that defined security relations between the two countries, and an agreement governing both bilateral trade and trade transiting Indian territory. The 1950 treaty and letters exchanged between the Indian government and Rana rulers of Nepal, stated that "neither government shall tolerate any threat to the security of the other by a foreign aggressor" and obligated both sides "to inform each other of any serious friction or misunderstanding with any neighboring state likely to cause any breach in the friendly relations subsisting between the two governments." These accords cemented a "special relationship" between India and Nepal. The treaty also granted Nepalese, the same economic and educational opportunities as Indian citizens in India, while accounting for preferential treatment to Indian citizens and businesses compared to other nationalities in Nepal. The Indo-Nepal border is open; Nepalese and Indian nationals may move freely across the border without passports or visas and may live and work in either country. However, Indians aren't allowed to own land-properties or work in government institutions in Nepal, while Nepalese nationals in India are allowed to work in Indian government institutions (except in some states and some civil services the IFS, IAS, and IPS). After years of dissatisfaction by the Nepalese government, India in 2014, agreed to revise and adjust the treaty to reflect the current realities. However, the modality of adjustment hasn't been made clear by either side.

Despite the close linguistic, marital, religious, and, cultural ties, at people to people level between Indians and Nepalese, since late 2015, political issues and border disputes have strained relations between the two countries with anti-Indian sentiment growing amongst the government and people of Nepal. Further because of border disputes between the two countries, a boundary agreement hasn't yet been ratified by either government.

Independent political history
1950-1970

This section possibly contains original research. Please improve it by verifying the claims made and adding inline citations. Statements consisting only of original research should be removed. (November 2019) (Learn how and when to remove this template message)
The foundation of relations between India and Nepal was laid with Indo-Nepalese friendship Treaty in 1950. In the 1950s, the Rana rulers of Nepal welcomed close relations with India, fearing a China-backed communist overthrow of their (Rana) autocratic regime.[citation needed] Rana rule in Nepal however collapsed within 3 months of signing the 1950 Indo-Nepal Treaty of Peace and Friendship, only to be replaced by the only pro-Indian party of the time - Nepali Congress. As the number of Indians living and working in Nepal's Terai region increased and the involvement of India in Nepal's politics deepened in the 1960s and after, so too did Nepal's discomfort with the special relationship.[citation needed] India's influence over Nepal increased throughout the 1950s. The Nepalese Citizenship Act of 1952 allowed Indians to immigrate to Nepal and acquire Nepalese citizenship with ease-a source of huge resentment in Nepal (This policy was not changed until 1962 when several restrictive clauses were added to the Nepalese constitution). Also in 1952, an Indian military mission was established in Nepal, which consisted of a Major General and 20 other Indian army personnel (later extended to 197 in total). At the same time, Nepal's Royal family's dissatisfaction with India's growing influence began to emerge, and overtures to China were initiated by Nepal as a counterweight to India. Further the Nepalese government, as a deliberate attempt to show pro-USA tilt in Nepalese foreign policy, established diplomatic ties with the state of Israel in June 1, 1960, while the Indian government supported Palestine and remained pro-USSR throughout the cold war.

Following the 1962 Sino-Indian border war, the relationship between Kathmandu and New Delhi thawed significantly. India suspended its support to India-based Nepalese opposition forces (opposing the dissolution of democratic government by King Mahendra). The defeat of Indian forces in 1962 provided Nepal with the breathing space and Nepal extracted several concessions in trade. In exchange, through a secret accord concluded in 1965, similar to an arrangement that had been suspended in 1963, India won a monopoly on arms sales to Nepal.

In 1969 relations again became stressful as Nepal challenged the existing mutual security arrangement and asked that the Indian security checkposts and liaison group be withdrawn. Resentment also was expressed against the 1950s TPF. India withdrew its military check-posts and liaison group consisting of 23 military personnel in 1970 from Nepal, although the treaty was not abrogated.

Tensions came to a head in the mid-1970s, when Nepal pressed for substantial changes in the trade and transit treaty and openly criticised Sikkim's 1975 annexation by India. In 1975 King Birendra Bir Bikram Shah Dev against the backdrop of Indian annexation of Nepal's close neighbor 'The Kingdom of Sikkim' proposed Nepal to be recognized internationally as a 'Zone of Peace' where military competition would be off limits. Nepal's proposal immediately received support from Pakistan and China, but not from India. In New Delhi's view, if the king's proposal did not contradict the 1950 treaty that the-then Indian government had signed with the Rana rulers of Nepal, it was unnecessary; if it was a repudiation of the special relationship, it represented a possible threat to India's security and could not be endorsed. In 1984 Nepal repeated the proposal, but there was no reaction from India. Nepal continually promoted the proposal in international forums and by 1990 it had won the support of 112 countries including the US, the UK, and France.

1970-1980
In 1978 India agreed to separate trade and transit treaties, satisfying a long-term Nepalese demand. However, much to the annoyance of Nepalese Royal Palace and in continued violation of the 1950s PFT, India consistently allowed the opposition parties of Nepal to use Indian soil to launch agitation against the Nepalese government and refused to endorse Nepal as a Zone of Peace. In 1988, when the two treaties were up for renewal, Nepal refused to accommodate India's wishes for a single trade and transit treaty stating that 'it violates the principle of freedom to trade'. Thereafter, both India and Nepal took a hard-line position that led to a serious crisis in India-Nepal relations. Nepalese leaders asserted the position that as per the UN charter, transit privileges were "a fundamental and a permanent right of a land-locked country" and thus India's demand for a single treaty was unacceptable. So, after two extensions, the two treaties expired on 23 March 1989, resulting in a virtual Indian economic blockade of Nepal that lasted until late April 1990. As time passed Indian economic sanctions over Nepal steadily widened. For example, preferential customs and transit duties on Nepalese goods entering or passing through India (whether imports or exports) were discontinued. Thereafter India let agreements relating to oil processing and warehouse space in Calcutta for goods destined to Nepal expire. Aside from these sanctions, India cancelled all trade credits it had previously extended to Nepal on a routine basis.

To withstand the renewed Indian pressure, Nepal undertook a major diplomatic initiative to present its case on trade and transit matters to the world community. The relationship with India was further strained in 1989 when Nepal decoupled its rupee from the Indian rupee which previously had circulated freely in Nepal. India retaliated by denying port facilities in Calcutta to Nepal, thereby preventing delivery of oil supplies from Singapore and other sources. In historian Enayetur Rahim's view, "the economic consequences of the dispute... were enormous. Nepal's GDP growth rate plummeted from 9.7% in 1988 to 1.5% in 1989. This had a lot to do with the decreased availability of goods. Shortly after the imposition of sanctions, Nepal experienced serious deficiencies of important goods such as coal, fuel, oil, medicine and spare parts. Nepal also suffered economically from higher tariffs, the closure of border points and the tense political atmosphere. From one of the most thriving economies in Asia, Nepal was now quickly finding itself in the league of World's poorest nation." Although economic issues were a major factor in the two countries' confrontation, Indian dissatisfaction with Nepal's decision to impose work permits over Indians living in Nepal and Nepal government's attempt to acquire Chinese weaponry in 1988 played an important role. India linked security with economic relations and insisted on reviewing India-Nepal relations as a whole. After failing to receive support from wider international community, Nepalese government backed down from its position to avoid the worsening economic conditions. Indian government, with the help of Nepalese opposition parties operating from India, managed to bring a change in Nepal's political system, in which the king was forced to institute a parliamentary democracy. The new government, led by pro-India parties, sought quick restoration of amicable relations with India.

1990s
The special security relationship between New Delhi and Kathmandu was re-established during the June 1990 New Delhi meeting of Nepal's prime minister Krishna Prasad Bhatarai and Indian prime minister V.P. Singh, after India ended its 13-month-long economic blockade of Nepal. During the December 1991 visit to India by Nepalese prime minister Girija Prasad Koirala, the two countries signed new, separate trade and transit treaties and other economic agreements designed to accord Nepal additional economic benefits.

Indian-Nepali relations appeared to be undergoing still more reassessment when Nepal's prime minister Man Mohan Adhikary visited New Delhi in April 1995 and insisted on a major review of the 1950 peace and friendship treaty which Nepal believed was enabling an ongoing demographic shift in Nepal's Terai region. In the face of benign statements by his Indian hosts relating to the treaty, Adhikary sought greater economic independence for his landlocked nation while simultaneously striving to improve ties with China.

In June 1990, a joint Kathmandu-New Delhi communique was issued pending the finalisation of a comprehensive arrangement covering all aspects of bilateral relations, restoring trade relations, reopening transit routes for Nepal's imports, and formalising respect of each other's security concerns. Essentially, the communiqu? announced the restoration of the status quo ante and the reopening of all border points, and Nepal agreed to various concessions regarding India's commercial privileges. Kathmandu also announced that lower cost was the decisive factor in its purchasing arms and personnel carriers from China and that Nepal was advising China to withhold delivery of the last shipment.

2000s
In 2005, after King Gyanendra took over, Nepalese relations with India soured. However, even after the restoration of democracy, in 2008, Prachanda, the Prime Minister of Nepal, visited India, in September 2008 only after visiting China, breaking the long-held tradition of Nepalese PM making India as their first port-of-call. When in India, he spoke about a new dawn, in the bilateral relations, between the two countries. He said, "I am going back to Nepal as a satisfied person. I will tell Nepali citizens back home that a new era has dawned. Time has come to effect a revolutionary change in bilateral relations. On behalf of the new government, I assure you that we are committed to make a fresh start."

In 2006, the newly formed democratic parliament of Nepal passed the controversial citizenship bill that led to distribution of Nepalese citizenship to nearly 4 million stateless immigrants in Nepal's Terai by virtue of naturalisation. While the Indian government welcomed the reformed citizenship law, certain section of Nepalese people expressed deep concerns regarding the new citizenship act and feared that the new citizenship law might be a threat to Nepalese sovereignty. The citizenship bill passed by the Nepalese parliament in 2006 was the same bill that was rejected by Late King Birendra in 2000 before he along with his entire family was massacred. Indian government formally expressed sorrow at the death of Late King Birendra of Nepal.

In 2008, Indo-Nepal ties got a further boost with an agreement to resume water talks after a 4-year hiatus. The Nepalese Water Resources Secretary Shanker Prasad Koirala said the Nepal-India Joint Committee on Water Resources meet decided to start the reconstruction of the breached Koshi embankment after the water level went down. During the Nepal PM's visit to New Delhi in September the two Prime Ministers expressed satisfaction at the age-old close, cordial and extensive relationships between their states and expressed their support and co-operation to further consolidate the relationship.

The two issued a 22-point statement highlighting the need to review, adjust and update the 1950 Treaty of Peace and Friendship, amongst other agreements. India would also provide a credit line of up to \$15 million to Nepal to ensure uninterrupted supplies of petroleum products, as well as lift bans on the export of rice, wheat, maize, sugar and sucrose for quantities agreed to with Nepal. India would also provide \$2 million as immediate flood relief.
In return, Nepal will take measures for the "promotion of investor friendly, enabling business environment to encourage Indian investments in Nepal."

2010s
In 2010 India extended a Line of credit worth US\$50 million & 80,000 tonnes of foodgrains. Furthermore, a three-tier mechanism at the level of ministerial, secretary and technical levels will be built to push forward discussions on the development of water resources between the two sides. Politically, India acknowledged a willingness to promote efforts towards peace in Nepal. Indian External affairs minister Pranab Mukherjee promised the Nepali Prime Minister Prachanda that he would "extend all possible help for peace and development."

However, in recent years, the increasing dominance of Maoism in Nepal's domestic politics, along with the strengthening economic and political influence of the People's Republic of China has caused the Nepalese government to gradually distance its ties with India, though Nepal still does support India at the UN. Prime Minister of India Narendra Modi visited Nepal in August 2014, marking the first official visit by an Indian prime minister in 17 years. During his visit, Indian government agreed to provide Nepal with US\$1 billion as concessional line of credit for various development purposes and a HIT formula, but he insisted that Indian immigrants in Nepal don't pose a threat to Nepal's sovereignty and therefore open border between Nepal and India should be a bridge and not a barrier. Nepal and India signed an important deal on 25 November 2014 as per which India will build a 900 MW hydropower plant at a cost of another US\$1 billion. An amount of US\$250 million has been granted to Nepal as a part of the agreements signed on 22 February 2016 for post-earthquake reconstruction.

A perpetual issue for many people of Nepali origin; the birthplace of Gautama Buddha has long been a cultural and social issue devoid from the political landscape of both Nepal and India. However, since the souring of relations between the two countries, the issue has been used to undermine relations between the two countries both politically and socially. The two-day-long International Buddhist conference in Kathmandu which ran from May 19-20, 2016 marked Vesak and the 2,560th birthday of the Buddha was also used to promote the Buddha's birthplace which lies in modern-day Nepal. The decision of the Nepal Culture Ministry to change the theme, "Preservation and Development of Buddhist Heritage of Nepal" with the sub-theme "Lumbini - Birthplace of Buddha" under the name "Lumbini - Fountainhead of Buddhism" was met with criticism from India which subsequently boycotted the conference due to this and on the back of China's supposed monetary involvement in the conference. Nepali Prime Minister, K.P. Oli told the media that the conference, "should help us make clear to the world that Buddha was born in Nepal and that Buddhist philosophy is the product of Nepal".

In early March 2017, the fatal shooting of a Nepali man who was protesting Indian-occupation on disputed territory between India and Nepal sparked protests in the capital Kathmandu. Indian troops had previously prevented a group of Nepalese farmers living along the border from completing a culvert in the disputed area which ultimately led to protests. It was considered rare for India to retaliate with gunfire.


Border disputes
Main article: Territorial disputes of India and Nepal
The Territorial disputes of India and Nepal include Kalapani 400 km2 at India-Nepal-China tri-junction in Western Nepal and Susta 140 km2 in Southern Nepal. Nepal claims that the river to the west of Kalapani is the main Kali river hence the area should belong to Nepal. But India claims that the river to the west of Kalapani is not the main Kali river, and, therefore the border there should be based on the ridge lines of the mountains Om Parvat to the east of the river. The river borders the Nepalese province of Sudurpashchim and the Indian state of Uttarakhand. The Sugauli Treaty signed by Nepal and British India on 4 March 1816 locates the Kali River as Nepal's western boundary with India. Subsequent maps drawn by British surveyors show the source of the boundary river at different places. This discrepancy in locating the source of the river led to boundary disputes between India and Nepal, with each country producing maps supporting their own claims. Indian government, however, from 1962 onward, forwarded the argument that border should be based on the ridge lines of the mountain Om Parvat. The Kali River runs through an area that includes a disputed area of about 400 km? around the source of the river although the exact size of the disputed area varies from source to source. The dispute intensified in 1997 as the Nepali parliament considered a treaty on hydro-electric development of the river. India and Nepal differ as to which stream constitutes the source of the river. Nepal has reportedly tabled an 1856 map from the British India Office to support its position. Kalapani has been controlled by India's Indo-Tibetan border security forces since the Sino-Indian War with China in 1962. In 2015, the Nepalese parliament objected an agreement between India and China to trade through Lipulekh Pass, a mountainous pass in the disputed Kalapani area, stating that the agreement between India and China to trade through Kalapani violates Nepal's sovereign rights over the territory. Nepal has called for the withdrawal of the Indian border forces from Kalapani area.

As the first step for demarcating Indo-Nepal border, survey teams from both countries located and identified missing pillars along the border, and, an agreement was reached to construct new pillars in some places. According to the Nepalese government estimates, of the 8000 boundary pillars along the border, 1,240 pillars are missing, 2,500 require restoration, and, 400 more need to be constructed. The survey teams conducted survey of the border pillars based on the strip maps prepared by the Joint Technical Level Nepal-India Boundary Committee (JTLNIBC). The JTLNIBC was set up in 1981 to demarcate the India-Nepal border and after years of surveying, deliberations and extensions, the Committee had delineated 98 per cent of the India-Nepal boundary, excluding Kalapani and Susta, on 182 strip maps which was finally submitted in 2007 for ratification by both the countries. Unfortunately neither country ratified the maps. Nepal maintained that it cannot ratify the maps without the resolution of outstanding boundary disputes, i.e. Kalapani and Susta. India, on the other hand, awaited Nepal's ratification while at the same time urging it to endorse the maps as a confidence building measure for solving the Kalapani and Susta disputes. In absence of a ratification, the process of completely demarcating the India-Nepal boundary could not be undertaken.

Border crossings
Main articles: Designated border crossings of India and Borders of India
Integrated check posts with immigration and customs facilities are:

Jogbani, Bihar
Sunauli, Uttar Pradesh
Rupaidiha, Uttar Pradesh
Taulihawa-Siddharthnagar (only for India and Nepalese citizens)
Jathi, Bihar

Since 2014 to enhance the collaborative relations between the two nations, Nepal and India started Trans-border bus services from New Delhi to Kathmandu connecting the nation's capital of both countries. The service is in operation by Delhi Bus Corporation (DTC) India and several other private Travel companies. At present(2019), Kathmandu to Delhi bus service, Kathmandu to Siliguri Bus service, Kathmandu to Varanasi, Delhi to Janakpur bus service are in operation.

Trade
India is Nepal's largest trade partner and the largest source of foreign investments, besides providing transit for almost entire third country trade of Nepal. India accounts for over two-third of Nepal's merchandise trade, about one-third of trade in services, one-third of foreign direct investments, almost 100% of petroleum supplies, and a significant share of inward remittances on account of pensioners, professionals and workers working in India In the year 2017-2018, Nepal's total trade with India was about US\$8.2 billion; Nepal's exports to India were about US\$446.5 million; and imports from India were about US\$7.7 billion.

Nepal's main imports from India are petroleum products (28.6%), motor vehicles and spare parts (7.8%), M. S. billet (7%), medicines (3.7%), other machinery and spares (3.4%), coldrolled sheet in coil (3.1%), electrical equipment (2.7%), hotrolled sheet in coil (2%), M. S. wires, roads, coils and bars (1.9%), cement (1.5%), agriculture equipment and parts (1.2%), chemical fertilizer (1.1%), chemicals (1.1%) and thread (1%). Nepal's export basket to India mainly comprises jute goods (9.2%), zinc sheet (8.9%), textiles (8.6%), threads (7.7%), polyester yarn (6%), juice (5.4%), catechue (4.4%), Cardamom (4.4%), wire (3.7%), tooth paste (2.2%) and M. S. Pipe (2.1%).

Human trafficking
Human trafficking in Nepal is a serious concern. An estimated 100,000-200,000 Nepalese in India are believed to have been trafficked. Sex trafficking is particularly rampant within Nepal and to India, with as many as 5,000-10,000 women and girls trafficked to India alone each year. The seriousness of trafficking of Nepalese girls to India was highlighted by CNN Freedom Project's documentary: Nepal's Stolen Children. Maiti Nepal has rescued more than 12,000 stolen Nepalese children from sex trafficking since 1993.

2015 Madhesi crisis and Nepal
Main article: 2015 Nepal fuel crisis

## Nepal-UK relation

1. Nepal and United Kingdom have celebrated 200 years of their relationship. How do you view this relationship and what recommendations, if you have, you wish to offer to take the subsisting relationship to the next level ?

\begin{solution}

Nepal established diplomatic relations with the United Kingdom in 1816. Treaty of Friendship between Great Britain and Nepal was signed in 1923 which further formalized relations between the two countries. Ever since the establishment of their diplomatic relations, friendship, mutual understanding, cordiality, cooperation and respect for each other's national interests and aspirations have characterized relationship between the two countries. The UK is also the first country in the world with which Nepal had established diplomatic relations and also the first to have established its Embassy in Kathmandu, the capital of Nepal. This is the country where Nepal had established its first diplomatic mission (Legation) back in 1934. It was elevated to the Ambassador level in 1947 AD.

The UK remained one of the top development partners of Nepal with the annual British aid on an increasing trend. Tourism, trade, education, and British Gurkha connection remained the key dimensions of the bilateral relations.

Since then, relations between the two countries have continued to grow, with a new Treay of Perpetual Peace and Friendship signed in 1950 which expanded areas of cooperation and an exchange of State Visits. Amicable relations continue today; Nepal continues to be the source of recruitment of Gurkha soldiers into the British army -- a tradition dating back to the nineteeth century but still an essential part of Britain's modern army -- and the UK remains one of the most significant providers of development assistance to Nepal.

As one of Great Britain's allies during the two world wars, Nepalese soldiers in hundreds of thousands fought and sacrificed their lives in many battlefields of the world, thus leaving a heritage of deep and sincere friendship in the history of two countries. The Gurkha soldiers are the most visible bridge between Nepal and the United Kingdom. It is to state that the Gurkha's service in the British army started on April 24, 1815, which is continuing till the date spanning over more than two hundred years. The solid foundation of the relation is built on the history of service, sacrifice and bravery of these Gurkha soldiers.

Nepal and United Kingdom are celebrating the bicentenary of bilateral relations between two countries. To mark the 200th year of the beginning of official contacts between the two countries in 1816, a number of programs and events from both sides have been organized in 2016-2017. There have been intermittent to and fro high level visits between Nepal and United Kindom since as early as 1960.

\textbf{Treaties/Memorandum of Understandings/Agreements between the UK and Nepal}

Bilateral consultation mechanism

With a view to enhancing the friendly cooperation and further promoting the bilateral relations Nepal and the United Kingdom have signed a MoU on 7th January, 2014. On behalf of Nepal and UK, Foreign secretary Mr. Arjun Bahadur Thapa and UK's Permanent Under Secretary Sir Simon Frazer signed the MoU for establishing the Consultation Mechanism at the Foreign and Commonwealth Office, London respectively. As per the MoU, both the parties will hold consultations at jointly decided intervals alternately in the capital of either country at an appropriate level as may be decided upon and hold discussion on all aspects of bilateral relations as well as on international or regional issues of mutual interest.

Finalized Agreements/MoU

\begin{itemize}
\item TIFA Agreement signed in 2011.
\item An agreement on promotion and protection of investment between Nepal and UK signed on March 2, 1993
\item Development Partnership Agreement between Nepal and UK, signed on December 2013. It supersedes the Technical cooperation agreement desiring to strengthen the traditional cooperation and cordial relation between Nepal and the UK signed on 31 May 1994.
\item Trade Agreement signed in 1965.
\end{itemize}

Agreements/MoU in Progress

\begin{itemize}
\item Bilateral Agreement on Avoidance of Double Taxation
\end{itemize}

\textbf{Economic and Technical Cooperation (Development Cooperation)}

The UK aid to Nepal in various fields of activities started in 1961. The United Kingdom has been offering fellowships to the Government of Nepal since 1950s. British volunteers are engaged in Nepal since 1964. These programmes have contributed to Nepal's need for specialised and trained manpower and also have developed important links between the people of the two countries. In order to better understand and address the issues of poverty in Nepal, in April 1999 Department for International Development (DFID) established an in-country office staffed by a multi-disciplinary team of both UK nationals and staff appointed in country. DFID presence in Nepal has greatly assisted in working with Government of Nepal in the development of understanding and establishment of networks that will promote opportunities for change.

Recently Development Partnership Arrangement to provide a transparent and mutual accountability framework between Nepal and the United Kingdom on development assistance was signed on December 2013. The assistance of British Government generally comes through the Umbrella Agreement. The first such agreement of Pound Sterling 12 million was signed on 23 September 1979 for the implementation of various projects. The UK Government’s Department for International Development (DFID) prepared an Operational Plan for Nepal during 2011-2016. This plan commits up to Pound Sterling 413 million of UK official development assistance during the period 2011-2016. All bilateral aid with Nepal is on a grant basis.

As per Development Cooperation Report 2014-2015 by Ministry of Finance, UK remained the top ODA provider (based on disbursement) with a total assistance of US dollars 168.07 million in the Fiscal Year 2014/2015.

DFID Technical Support has been instrumental in promoting foreign direct investment especially in large hydropower project through Investment Board Nepal for the last few years. This very programme has provisioned of supporting IBN to promote private investment in the country. Likewise there are provisions of continuing support to the second and third phases of Financial Sector Reform Programme of the Government initiated few years back. The program will last for six years from 2015 to 2020.

The DFID Nepal's operational Plan is divided into four main areas: governance and security, inclusive wealth creation, human development (basic services including education and health), and climate change/disaster management. The UK has assisted Nepal in the areas of livelihoods, e.g. agriculture, forestry, transport and communications, local development; basic services, e.g. education, health, water supply and sanitation; good governance, human rights and peace building efforts.

\textbf{Earthquake, 2015}

Nepal received generous support and assistance from the Government of the United Kingdom in the aftermath of the earthquake of 25 April 2015. It responded to the Nepal earthquakes immediately with the deployment of Eight Disaster Response Specialists under Rapid Response Facility and with the release of GBP 5 million. The United Kingdom Government pledged USD 110 million for the reconstruction and rebuilding of Nepal. 

\textbf{Trade}

Nepal and UK signed trade agreement in 1965. Despite our extensive engagements and linkages, both at the level of government and, people in the backdrop of our long-standing friendly and cooperative relations, trade and investment relations between the two countries have largely remained way below its actual potential.

With high imbalance and elements of unpredictability, this is, of course, a typical feature of a trade relation between a developed and least developed country. Nepal faced a trade deficit of 142,182,856 Rupees in the first eight month of 2016. The total export to UK stands at 1,256,018,669 Rupees while the total import stands at 1,398,201,525. It is for this reason that Nepal places high importance to directing foreign development cooperation in areas which help enhancing our productive capacity. Aid for trade is, therefore, another preferred area for us in our development cooperation. 

The major items of import from UK are: Motor car, vehicle, parts of aeroplane and helicopter, Whiskies, Malt not roasted, Sweets biscuits, Chocolate in blocks, slab or bar etc. Major Nepalese exports to UK are Pashmina shawls, goatskin, leather goods, Nepalese paper and paper products, woollen carpets, handicrafts, ready-made garments, silverware and jewellery. Likewise, major imports from UK are copper scrap, hard drinks, cosmetics, medicine and medical equipment, textiles, copper wire rod, machinery and parts, aircraft and spare parts, scientific research equipment, office equipment and stationery.

Exchange of visits by trade delegations from Nepal and Britain has added a new dimension to the commercial relations between Nepal and Britain. Nepal-Britain Chamber of Commerce and Industry is active in promoting trade and investment between Nepal and UK.

\textbf{Tourism}

A sizeable number of British tourists come to Nepal every year for trekking and mountaineering and other leisurely activities. Given our historical linkages and increasing people-to-people contacts, the prospects for increasing the tourist arrival from UK in Nepal are quite promising.

UK's support and cooperation in line with our broader policy priorities will be much appreciated, especially in construction and upgradation of tourism infrastructure with focus on tourist safety. DIFID’s recent involvement and interest in tourist security, trekkers tracking, and maintenance of damaged trekking trails, including the Great Himalayan Trail, is most welcome.

Embassy of Nepal in London is planning to organize the many tourism promotional programme to increase the number of tourists from UK.

\textbf{Consular activities}

Embassy of Nepal in London involves in various consular service ranging from passports, visas, Travel Document, NRN Card, Verification, Attestation and Power of Attorney. During Fiscal Year 2075/76, Embassy of Nepal in London generated GBP 542048.72 (NRS 7,73,71,510.41) revenue.

\textbf{Investment}

Foreign investment commitment from UK stands at 1663 million rupees till 2013/14. The major investment is in the areas of banking, tourism, education, technology. An agreement for the promotion and protection of investment between Nepal and UK was signed on March 2, 1993.

There are some British joint ventures in the areas of hotel, travel and trekking, tea production, education, garment, bio-technology and consultancy. These are significant figures, but do not reflect the true potential. There are many British and Non Resident Nepalese (NRN) entrepreneurs who are still making trade and investment successes in Nepal. Standard Chartered Bank and Unilever are two major British companies who have made a huge return from their investment in Nepal in the last 20 years.

An agreement on promotion and protection of investment between Nepal and UK signed on 02 March 1993 provides a framework to further expand cooperation in this field. In this context, the proposal for signing another agreement on avoidance of double taxation will further help boost the flow of FDI between the two countries.

\textbf{Foreign employment and British Gurkha}

Thousands of Nepalese are working at service sectors like hospitals, university, hotels and restaurants in UK. About 200 Nepalese are recruited as Maritime Security Guards in UK. About 150,000 Nepalese are living in UK. Many Nepalese belong to Ex-Gurkha Servicemen and their families.

British Gurkhas is a fully integrated part of the British Armed Forces. It constitutes an important element in Nepal-Britain relations.  Over 160,000 Gurkhas were enlisted in the Gurkha Brigade and other units of the Indian Army during the First and Second World Wars. In recognition of their distinguished service, the British Gorkhas servicemen from Nepal have won 13 Victoria Crosses (VC), the highest British gallantry honour.

\textbf{Cultural Cooperation}

British Council in Nepal is working to extend cultural relations between UK and Nepal. Similarly, Nepalese diaspora and Gurkha soldiers are visible bond who have interlinked the Nepalese culture and traditions in UK.

\textbf{Education cooperation}

UK is supporting US dollars 260,012 for the education of marginalised girl in Kailali district of Nepal. DFID was the core education funding agency in Nepal, supporting the foundations of education values. Active as a School Sector Reform Plan (SSRP) pooling Development Partner. With Education for All overall goals, the SSRP objectives were to 
\begin{enumerate}
\item ensure access and equity in primary education; 
\item improve the efficiency and institutional capacity of primary education; and 
\item enhance the quality and relevance of basic primary education for children and illiterate adults.
\end{enumerate}

In 2013, DFID committed around GBP 2 million to establish 810 additional girls' toilet and water supplies/WASH facilities across 18 districts selected based on low indicators in hygiene and sanitation with an implementation date which was extended to July 2015.

The British Government has been regularly providing scholarships in different areas for the development of human resource in Nepal since 1950s. Britain is offering Chevening Award to Nepalese from many years. A lot of Nepalese students are pursuing higher level studies in the UK. 

\textbf{Security cooperation}

UK has provided support for upgrading of Nepal Army Birendra Peace Operations Training Centre (BPOTC) located at Panchkhal (45 km East of Kathmandu). It has also provided Explosive Ordinance Device (EOD) related Improvised Explosive Device Disposal (IEDD) related Special Training to Nepal Army. UK is continually providing the special training courses to Nepal Army officials.

High level visit from Nepal Army and British Army are regularly taking place in UK and Nepal respectively.

\textbf{Nepalese students in UK}

\end{solution}

## Nepal-USA relation

2. Discuss about the bilateral US relations with Nepal

**Solution:**

The United States recognized the Kingdom of Nepal on April 27, 1947, when Joseph C. Satterthwaite presented a letter from President Harry S. Truman to then king Tribhubana of Nepal. Satterthwaite was on a special diplomatic mission to Nepal as personal representative of the President. The two countries established diplomatic relations in 1948. Bilateral relations are friendly, and U.S. policy objectives toward Nepal center on helping it build a peaceful, prosperous, resilient and democratic society. Primary U.S. objectives in Nepal include supporting a stable, democratic Nepal that respects the rule of law; promoting investor-friendly economic development; and improving disaster risk management systems.

The United States enjoys a strong and positive relationship with Nepal. Years of diplomatic, development, and military engagement have advanced U.S. interests in transitioning Nepal into a more peaceful, stable democracy with significant economic potential. Since the end of its 10-year civil war in 2006 and the devastating earthquakes of 2015, Nepal has successfully transitioned into a full-fledged constitutional federal republic grounded in a constitution promulgated in 2015. With the recent formation of a new government, Nepal may now be on the cusp of a period of much-needed political stability.

Nepal has sought a bilateral consultation mechanism with the United States and has signed similar agreements with other countries like Australia in summer 2017. Such a forum might include as topics: Millenium Challenge Cooperation (MCC) coordination and implementation; trade (TPS, technical assistance, etc.); security and defense cooperation; and humanitarian assistance and disaster response.

To improve Nepal's economic situation, the MCC signed, in 2017, a \$500 million Compact with Nepal to expand Nepal’s electricity transmission infrastructure and improve its road maintenance regime. The Nepali government has committed another \$130 million for a program total of \$630 million. The Compact will build 300 kilometers (km) of high-voltage electric transmission lines, three substations, perform enhanced road maintenance on 305 km of strategic highways, and provide technical assistance to the national electric utility, the new electricity regulator, and the Department of Roads. The Compact is entered into force after the end of FY 2019.

U.S. assistance has been critical to helping Nepal rebuild after the devastating 2015 earthquake and remains committed to building Nepal's resilience in the event of any future disaster. The United States has provided over \$190 million for earthquake relief, recovery, and reconstruction. While these commitments have exceeded our initial pledge of \$130 million made at the International Conference on Nepal's Reconstruction in June 2015, significant recovery needs remain. To date, the United States has built 36 schools and hospitals; has directly helped rebuild over 16,000 homes; trained 260,000 people in safer construction; and developed policies, systems, and controls to ensure that $8.6 billion in reconstruction results in safer structures for all. In addition to rebuilding a safer Nepal, we are working to help Nepal institutionalize all lessons learned from the 2015 earthquake. We are also helping Nepal to implement its new disaster management law and stand up a new National Disaster Management Authority. We are further supporting Nepal as it introduces federalism by working with newly elected local governments to implement their own disaster management plans—thus helping local authorities meet commitments made to their constituencies. These efforts will help Nepal on its journey to self-reliance.

The United States has also committed security assistance to Nepal, working with the Nepali Army to strengthen their peacekeeping and disaster response capabilities.

The United States and Nepal have signed a trade and investment framework agreement, providing a forum for bilateral talks to enhance trade and investment, discuss specific trade issues, and promote more comprehensive trade agreements between the two countries. In 2016, Nepal became one of few countries in the world with a single-country trade preference program with the United States. Principal U.S. exports to Nepal include agricultural products, aircraft parts, optic and medical instruments and machinery. U.S. imports from Nepal include carpets, apparel and jewelry.
