### Foreign Investment

\begin{questions}

\question What are the prospects of Foreign Investment in Nepal ?

\begin{solution}
Nepal has been pursuing a liberal foreign investment policy and been striving to create an investment- friendly environment to attract FDIs into the country. Our tax slabs one of the lowest and our position is fairly good in ease of doing business. Profitable areas of investment include hydropower, industrial manufacturing, services, tourism, construction, agriculture, minerals and energy.

Nepal encourages foreign investment both as joint venture operations with Nepalese investors or as 100 per cent foreign-owned enterprises. The few sectors that are not open to foreign investment are either reserved for national entrepreneurs in order to promote small local enterprises and protect indigenous skills and expertise or are restricted for national security reasons. Approval of the GoN is required for foreign investment in all sectors. No foreign investment is allowed in cottage industries. However, no restriction is placed on transfer of technology in cottage industries.

Most investment gurus believe that agriculture and mining will produce the best returns around the world in the next 20-30 years. Food prices are expected to go up because the growing middle class population in emerging markets will demand more expensive food including meat and more jewelry. Worldwide inflation will be higher than expected; so holding precious metals will be better than holding cash.

Nepal is close to India and China which will have the largest surge in the middle class population in the history of the world. As families become smaller and wealthier, they will start eating well. Meat consumption will rise. It will take more agricultural resources to produce more meat.

These families will also be more interested in traveling. Due to proximity, Nepal is a prime destination for both Chinese and Indian tourists.

Investment opportunities in Nepal

Land, Land and More Fertile Land

Although land prices in the Terai and rural areas in Nepal are starting to go up, they are still cheap. Land can provide dividends in terms of crops while waiting for the value to go up in a couple of decades.

Jeremy Grantham, a famous investor who predicted the 2007 financial meltdown, predicts that state-of-the-art organic farming is the best investment in the world now. In Nepal, we can combine both traditional and modern organic farming techniques to grow food in anticipation of the rapid food price increase.

Tourism Investments

Nepal is the country in the world which is sandwiched between two fastest growing large economies. India and China will have a huge growth in middle class population eager to travel. Nepal can tap the growing tourism market by anticipating where Chinese and Indian tourists may want to spend.

Buying shares in tourism-related stocks such as hotels, airlines or restaurants is a passive way to tap this potential. You can also open a resort or travel agency in anticipation of the boom. If you open up your own venture, the key to success is to be appealing and different from others.

Hydropower

Potential of hydropower in Nepal is huge. While investing in large-scale hydropower plants may need huge sum, it is possible to buy shares in related companies when they go public.

Several hydropower projects are underway in Nepal. In the next 10 years, several of them will become public. This will provide a good opportunity for an ordinary investor without millions of rupees to invest. For large scale investors, projects await in number. Nepal concluded a much awaited Power Trade Agreement with India in 2014 paving the way for trade of electric power just like other marketable commodities. This now ensures predictability of market once electricity is produced.

Outsourcing from US, Europe and Australia

Most foreign companies are looking to outsource programming, research or labor-intensive work to developing countries. These companies will save a substantial amount of money by doing so. Such outsourcing opportunities exist especially in web programming because of a large number of students interested in computer engineering in Nepal.

Medical Tourism

Nepal has produced some of the best doctors around the world. Surgeons from Nepali hospitals also do surgeries in Singapore, UK and USA. It is true that Nepali hospitals lack the infrastructure and equipment found in developed countries, but the quality of doctors is high.

So a good opportunity to invest is in medical tourism in Nepal. Healthcare services in the developed world is expensive. A simple bypass surgery costs around a hundred thousand dollars there, while the same surgery can be done in Nepal at a fraction of the price.

Since Nepal is a country endowed with natural beauty, visiting Nepal for pleasure as well as medical reasons should be an attraction.

Investment Board

With the view to attracting foreign as well as domestic Investment to boost the economy, the Government of Nepal has constituted a high level Investment Board, chaired by the Prime Minister of Nepal. The main objective of this board is to facilitate investors in investing in the potential sectors in Nepal. It provides one window facilities to the investors.

These are a number of investment ideas that can generate significant returns over the years. There will be even more opportunities in Nepal as the middle class population grow in Nepal. Rate of returns on investment in Nepal is high.

source: \url{https://mofa.gov.np/about-nepal/investment-in-nepal/}
\end{solution}

\end{questions}

### Terrorism

Terrorism in its broadest sense, describes the use of intentionally indiscriminate violence as a means to create terror, or fear, to achieve political, religious or ideological aim. It is used in this regard primarily to refer to violence against peacetime targets or in war against non-combatants.

Terrorism has been practiced by political organizations with both rightist and leftist objectives, by nationalistic and religious groups, by revolutionarie, and even by state institutions such as armies, intelligence services, and police.

Terrorism is not legally defined in all jurisdictions; the statutes that do exist, however, generally share some common elements. Terrorism involves the use of threat of violence and seeks to create fear, not just within the direct victims but among a wide audience. The degree to which it relies on fear distinguishes terrorism from both conventional and guerilla warfare. Although conventional militiary foreces invariably engage in psychological warfare against the enemy, their principal means of victory is strength of arms. Similarly, guerrilla forces, which often rely on acts of terror and other forms of propaganda, aim at military victory and occassionally succeed (e.g. the Viet Cong in Vietnam and the Khmer Rouge in Cambodia). Terrorism proper is thus the systematic use of violence to generate fear, and thereby to achieve political goals, when direct military victory is not possible. This has led to some social scientists to refer to guerrilla warfare as the "weapon of the weak" and terrorism as the "weapon of the weakest".

Terrorism has been described variously as both a tactic and strategy; a crime and a holy duty; a justified reaction to oppression and an inexcusable abomination. Obviously, a lot depends on whose point of view is being represented. Terrorism has often been an effective tactic for the weaker side in a conflict. As an asymmetric form of conflict, it confers coercive power with many of the advantages of military force at a fraction of the cost. Due to secretive nature and small size of terrorist organizations, they often offer opponents no clear organization to defend against or to deter.

This is why pre-emption is being considered to be so important. In some cases, terrorism has been a means to carry out a conflict without the adversary realizing the nature of the threat, mistaking terrorism for criminal activity. Because of these characteristics, terrorism has become increasingly common among those pursuing extreme goals throughout the world. But despite its popularity, terrorism can be a nebulous concept.

The US Department of Defense defines terrorism as "the calculated use of unlawful violence or threat of unlawful violence to inculcate fear; intended to coerce or to intimidate governments or societies in pursuit of goals that are generally political, religious, or ideological."

The UN produced the following definition of terrorism in 1992; "An anxiety inspiring method of repeated violent action, employed by semi-clandestine individual, group or state actors, for idiosyncratic, criminal or political reasons, whereby -- in contrast to assassination -- the direct targets of violence are not the main targets."

The strategy of terrorists is to commit acts of violence that draws the attention of the local populace, the government, and the world to their cause. The terrorists plan their attack to obtain the greatest publicity, choosing targets that symbolize what they oppose.

The effectiveness of the terrorist act lies not in the act itself, but in the public's or governments reaction to the act. For example, in 1972 at the Munich Olympics, the Black September organization killed 11 Israelis. The Israelis were the immediate victims but the true target was the estimated 1 billion people watching the televised event. Those billion people watching were to be introduced to fear -- which is terrorism's ultimate goal. The introduction of this fear can be from the threat of physical harm/a grizzly death, financial terrorism from the fear of losing money or negative effects on the economy, cyber terrorism harming the critical technological infrastructures of society and psychological terrorism designed to influence people's behavior.

There are three perspectives of terrorism: the terrorist's, the victim's, and the general public's. The phrase "one man's terrorist is another man's freedom fighter" is a view terrorists themselves would gladly accept. Terrorists do not see themseleves as evil. They believe they are legitimate combatants, fighting for what they believe in, by whatever means possible to attain their goals. A victim of a terrorist act sees the terrorist as a criminal with no regard for human life. The general public's view though can be the most unstable. the terrorists tke great pains to foster a Robin Hood image in hope of swaying the general public's point of view towards their cause. This sympathetic view of terrorism has become an integral part of their psychological warfare and has been countered vigourously by governments, the media and other organizations.

Technolgical advances, such as automatic weapons and compact electrically detonated explosives, gave terrorists a new mobility and lethality, and the growth of air travel provided new methods and opportunities. Terrorism was virtually an official policy in totalitarian states such as those of Nazi Germany under Adolf Hitler and the Soviet Union under Stalin. In these states arrest, imprisonment, tourture, and execution were carried out without legal guidance or restraints to create a climate of fear and to encourage adherece to the national ideology and the declared economic, social, and political goals of the state.

One of the deadliest terrorist strikes to date were the September 11 attacks of 2001, in which suicide terrorists associated with al-Qaeda hijacked four commercial airplanes, crashing two of them into the twin towers of the World Trade Center complex in the New York city and the third into the Pentagon building near Washington D.C.; the fourth plane crashed near Pittsburgh, Pennsylvania. The crashes destroyed much of the World Trade Center complex and a large portion of one side of the Pentagon and killed more than 3000 people.

Terrorism appears to be an enduring feature of political life. Even prior to the September 11 attacks, there was widespread concern that terrorist might escalate their destructive power to vastly greater proportions by using weapons of mass destruction -- including nuclear, biological, or chemical weapons -- as was done by the Japanese doomsday cult AUM Shirnrikyo, which released nerve gas into a Tokyo subway in 1995.

Factors conducive to terrorism

1. Poverty
2. Globalization
3. Legitimate grievances and failure of governments.
4. Humiliation
5. Lack of democracy, and widespread and systematic violation of human rights
6. Lopsided foreign policy
7. Failed state governance and authority

Goals, strategies, adn weapons of terrorism

1. Social and political justice
2. Self determination
3. Racial superiority
4. Foreign policy
5. Publicty
6. Demoralized governments

Costs associated with terrorism are so widespread, complex, and intangible that they are virtually impossible to measure. Individuals, families, governments, companies and non-state actors bear the time, money and resource costs of terrorism to varying degrees. Migration, trade, travel and interpersonal relations are affected. It is generally believed that the financial crisis and the global recesssion were caused in by policies adopted by the Bush administration to fight global terrorism, including wars in Afganistan and Iraq.

Kinds of terrorism

Although the types of terrorism tend to overlap, they vary in their implications and affect us in different ways. For example, the indiscriminate nature of global terrorism contrasts sharply with domestic terrorism aimed at specific groups or governments.

1. Domestic terrorism occurs within the borders of a particular country and is associated with extremist groups.
2. Nationalist terrorism is closely associated with struggles for political autonomy and independence.
3. Religious terrorism grows out of extreme fundamentalist religous groups that believe that God is on their side and that their violence is divinely justified and inspired.
4. State terrorism is a cold, calculated, efficient and extremely destructive form of terrorism, partly because of the overwhelming power at the disposal of governments.

Leading terrorist organizations

- ISIS (part of northern Iraq and parts of Western Syria)
- Al-Qaeda (Afganistan)
- Taliban
- Boko Haram (now sworn to ISIS; Nigeria)
- Lashkar-e-toa (Pakstan)
- Hezbollah (Lebanon)
- Al-Shabaab
- Hamas (Palestine)
- Naxal/Naxalites (India)
- Irish Republican Army

No cause justified terrorism. The world must repond and fight vigillantly with this evil that is intent on threatening and destroying our basic feedoms and way of life. The complexity of terrorists requires employing a wide variety of instruments to combat it. It addition to military, traditional law enforcement, intelligent responses, and global cooperation has become obvious to counter terrorist attacks.

The most prevalent response to terrorism is the use of force, both domestically and internationally. Besides, reduction in the production of weapons of mass destruction and control over media and technology can be effective.

We must retaliate forcefully and successfully in order to reassure the world of our confidence as a great power, and our ability to retain that status. Lastly, and practically, we must explore the possibilities of terrorism that exist and attempt to grasp the actual threat that these possibilities realistically pose for us.

### Globalization

Globalisation is the process of interaction and integration among people, companies, and governments worldwide. As a complex and multifaceted phenomenon, globalization is considered by some as a form of capitalist expansion which entails the integration of local and national economies into a global, unregulated market economy. Globalization has grown due to advances in transportation and communication technology. With the increased global interactions comes the growth of international trade, ideas, and culture. Globalization is primarily an economic process of interaction and integration that's associated with social and cultural aspects. However, conflicts and diplomacy are also large parts of the history of globalization, and modern globalization.

Economically, globalization involves goods, services, the economic resources of capital, technology, and data. Also, the expansions of global markets liberalize the economic activities of the exchange of goods and funds. Removal of cross-border trade barriers has made formation of global markets more feasible.[citation needed] The steam locomotive, steamship, jet engine, and container ships are some of the advances in the means of transport while the rise of the telegraph and its modern offspring, the Internet and mobile phones show development in telecommunications infrastructure. All of these improvements have been major factors in globalization and have generated further interdependence of economic and cultural activities around the globe.

Though many scholars place the origins of globalization in modern times, others trace its history long before the European Age of Discovery and voyages to the New World, some even to the third millennium BC. Large-scale globalization began in the 1820s. In the late 19th century and early 20th century, the connectivity of the world's economies and cultures grew very quickly. The term globalization is recent, only establishing its current meaning in the 1970s.

Three major dimensions of globalization can be differentiated. They are:

Economic globalization

It is the increasing economic interdependence of national economies across the world through a rapid increase in cross-border movement of goods, services, technology, and capital. Whereas the globalization of business is centered around the diminution of international trade regulations as well as tariffs, taxes, and other impediments that suppresses global trade, economic globalization is the process of increasing economic integration between countries, leading to the emergence of a global marketplace or a single world market. Depending on the paradigm, economic globalization can be viewed as either a positive or a negative phenomenon. Economic globalization broadly comprises: globalization of production and market but also includes competition, technology, and corporations and industries.

Cultural globalization

Cultural globalization refers to the transmission of ideas, meanings, and values around the world in such a way as to extend and intensify social relations. This process is marked by the common consumption of cultures that have been diffused by the Internet, popular culture media, and international travel. This has added to processes of commodity exchange and colonization which have a longer history of carrying cultural meaning around the globe. The circulation of cultures enables individuals to partake in extended social relations that cross national and regional borders. The creation and expansion of such social relations is not merely observed on a material level. Cultural globalization involves the formation of shared norms and knowledge with which people associate their individual and collective cultural identities. It brings increasing interconnectedness among different populations and cultures. Cross-cultural communication, cultural diffusion and religious thought-schools are the major aspects of cultural globalization. Sports too bear the spirit of globalization; for eg., the FIFA World Cup is the most widely viewed and followed sporting event in the world, exceeding even the Olympic Games; a ninth of the entire population of the planet watched the 2006 FIFA World Cup Final.

Political globalization

Political globalization refers to the growth of the worldwide political system, both in size and complexity. That system includes national governments, their governmental and intergovernmental organizations as well as government-independent elements of global civil society such as international non-governmental organizations and social movement organizations. One of the key aspects of the political globalization is the declining importance of the nation-state and the rise of other actors on the political scene. Adherence to or practice of intergovernmentalism, multi-level governance and multiple citizenship reflect today's globalized politics, although it should also be noted that some countries, like North Korea, have embraced isolationist policies.

Aside from the the above mentioned aspects, globalization touches upon a wide range of issues including population migration, information exchange, environmental protection.

Although globalization, according to many political scientists, is not a new phenomenon and that countries pursued it in various ways since the birth of the nation state, nobody denies the fact that the current phase of globalization is different-- different in the sense that it unleashed three major trends. The first is denationalization of the state involving major changes in the power of the legislature, the executive and the judiciary and shifts in the relative weight of financial, technological, environmental, security and other organs. The second is the de-statization of politics making the state's involvement in society less hierarchical, decentralized, poly-centric and multi-tiered involving both territorial and functional units. And, finally, the internationalization of the policy regime increasing the strategic significance of the international context of domestic state action and blurring the distinction between domestic and foreign policy regimes. The main issue of "governance in a global economy is the loss of monetary and fiscal options for the nation state and subservience to rules sometimes made by the international trade and financial interests". Argentina presents an extreme case of the loss of monetary sovereignty. To participate in the global economy, it surrendered its economic policy prerogative to the US. The communications revolution has truly made it possible for different global power centers to execute their agendas almost immediately. If this has opened new unforeseen opportunities for global peace and prosperity, at the same time, risks have also multiplied by as many times.
