
## National security

The promulgation of the much-awaited constitution by the Constituent Assembly in September and the subsequent Madhes movement have revealed some complicated and sensitive security threats for Nepal as a nation-state. Ensuring national unity, territorial integrity, people's sovereignty and citizens' security have always been highly sensitive issues for Nepal. But the Madhes movement and subsequent ‘unofficial' blockade by India have demonstrated some critical internal as well as external security threats for Nepal, undermining its sovereignty, independence and citizens' security. Therefore, taking into consideration the emerging global, regional and domestic security and political contexts, Nepal needs to objectively identify its internal and external threats and should draft a comprehensive national security policy sooner than later, if Nepal is to survive as a nation-state and ensure security of its citizens.

External threats

Following the end of the Cold War and the successive wave of democracy and globalisation, the theoretical concept of security has significantly changed. There has been a redefinition of the traditional notions of security, threat perspectives and role of security agencies. Despite the changing definition of security, the principle external threats remain unchanged. Although Nepal has not fought a war with any country after the Sugauli Treaty excluding a brief war with Tibet in 1856, it is not an external threat-free country. The recent coercive diplomacy and blockade by India have proved it. The global and regional powers' strategic rivalry vis-a-vis Nepal has significant internal and external security implications that have, to some extent, undermined Nepal's sovereignty and independence.

External military intervention is less likely in the 21st century. But according to the realist school of thought, for powerful countries everything is fair to achieve their national interests against weak and developing countries; hence they can go to any extent. Protecting national interests, territorial integrity and people's sovereignty are crucial issues for a buffer state like Nepal sandwiched between two emerging global powers —India and China. Nepal should take into account its geo-political sensitivity and geo-strategic importance while drafting national security and foreign policy without hurting their fundamental strategic and diplomatic interests. Therefore, Nepal should maintain diplomatic and strategic balance with both its neighbours and with other global powers. Otherwise, it may transform into a battleground for regional and global powerhouses.

Like military intervention and economic blockade, border encroachment, international terrorism, religious fundamentalism, refugee flows, migration, trans-border crimes, arms smuggling and climate change are equally serious external threats to Nepal. Nepal also has border disputes and a trade deficit with India, which  are not conducive to cordial Nepal-India relations. Therefore, Nepal needs to develop commercial as well as strategic physical infrastructure with both neighbours in line with its national interests and national security to achieve its strategic objectives.   

Internal threats

Nepal is not an external threat-free country, but analysing the emerging threats, internal threats seem more sensitive, complicated and challenging, as more than 17,000 Nepali people lost their lives in a decade-long internal conflict, and the ongoing violent Madhes movement has created some crucial threats. However, the current Madhes movement is a political movement; hence, the government should not suppress it. Instead, the government should resolve the problem through dialogue addressing the movement's legitimate demands. But the movement has exemplified some critical security threats that the government needs to address urgently. If it fails to do so,  there is a high possibility of instigating another kind of conflict that may turn into a multidimensional (ideological, religious, communal, ethnic, regional) one sooner or later. The potential multidimensional conflict may weaken the centuries-old social, cultural and religious harmony of Nepal. If the government and political parties cannot deal with these very sensitive issues appropriately, there might be a turn towards religious and ethnic conflicts and secessionist movements.  

Violence and crime seem to be a legacy of the decade-long conflict, and they seem to have become an integral part of society, destroying the very Nepali identity of peace and harmonious existence. Analysing the facts and figures, there are some conventional threats like poverty, unemployment, economic disparity, armed-conflict, criminal groups, arms infiltration, impunity and domestic violence. But some threats like environmental degradation, climate change, natural disaster, food insecurity, migration, etc., are unconventional. Likewise, non-state actors have been weakening and paralysing the state agencies and causing threats that may well emerge as the most serious ones in the future.

Redefining security policy

National security and people's security are very serious, challenging and complicated issues for Nepal. But, unfortunately, Nepal does not have a comprehensive written national security policy, and it has been following ad-hoc and outdated approaches even after the historic change of 2006. The successive governments and political parties did not pay heed to national as well as people's security policy; they merely beat the drum of ultranationalism and national independence for public consumption. Following the promulgation of the constitution, it is high time Nepal drafted a comprehensive national security policy. The new policy should be redefined in line with the changed political and security contexts for three reasons.

First, Nepal is in the process of transforming into a federal republic state from a feudal and unitary kingdom, and the security threats for these two types of regimes are fundamentally different. Second, the new constitution has defined human security as a guiding principle of national security, according to which, the role of the state is not only limited to defending its territory, but also to ensure freedom, human rights, peace and security of its citizens. The concept of security, therefore, has shifted focus  from state to human-centric approaches. Third, the internal and external threats to Nepal seem to be more complicated and challenging than before, so the new policy should clearly identify both threats and outline strategies to  address them.

To conclude, the new government needs to draft and implement a national security policy to safeguard national unity, territorial integrity, people's sovereignty and national interests based on national consensus. Moreover, the policy should embrace the fundamental principles of democracy, rule of law, human rights, and protect the long cherished identity, values and cultures of Nepal. The policy should also recognise the diversity and plurality of Nepali society, but it should not be used as a tool to suppress the people on the pretext of national security.

Wagle is a research fellow of Birmingham University, UK

source: \url{https://kathmandupost.com/opinion/2016/01/08/defending-the-nation}

## Order on the border

Nepal and India have an open border of more than 1,700 km. India borders Nepal on three sides—east, west and north—while China's Tibet Autonomous Region is to the north; thus sandwiching Nepal between the two Asian giants. In territorial, demographic, developmental and strategic terms, there is no comparison between Nepal and its two neighbours. For a variety of reasons, these asymmetries have also provided Nepal with a sense of national security, given that the quirks of today's international politics is impacted as much by conventional strategic competition for great power status and hegemony as by rising non-state actors whose orientation is determined by religious fundamentalism, ethnicity and de-ideologised politics.

Open history

The open border between Nepal and India is neither a new phenomenon nor an imposition by the inequality of powers. It is not a porous border but it can be called an open border for a variety of reasons: unrestricted movement of the peoples of India and Nepal; more-or-less equal treatment meted out

to Nepalis in India and Indians in Nepal; and continuing historical relations in political, social, economic and other fields. The post Sugauli Treaty relationship cemented these political, economic and security relations in the absence of any third power in Nepal's vicinity.

The de facto Chinese presence came much later in 1949, following the emergence of Red China. Yet, such a change did not disturb Nepal-India bilateral relations, although Nepal had to make some adjustments to the emergent geopolitical context. The Nepal-India Treaty of Peace and Friendship of 1950 was only a modified version of the 1923 Nepal-Britain Treaty. And as of today, the 1950 treaty continues to provide a framework for relationships despite being called an 'unequal treaty' concluded by the beleaguered Rana rulers.

It is interesting to note that this treaty does not specifically mention 'open border', as it simply deals with the special privileges to be granted to the citizens of both countries. Debates relating to the movement of peoples and its implications for changing the demographic balance in Nepal saw their peak in the 1980s and 90s with political party leaders, academics and policymakers trying to link up the open border with the free movement of peoples. Arguing that continuity for such a relationship would pose a serious threat to Nepal's security, they demanded an end to the open border.

Contrary to such views, an American political scientist, Myron Weiner, had already made some observations on the basis of his research and had concluded India to be "a safety-valve" for Nepal. His article, 'The Political Demography of Nepal', was presented in a seminar in Nepal in 1971 and was published in Asian Survey (Berkeley) in 1973. From time immemorial, the movement of Nepalis and Indians has continued uninterruptedly without losing Nepal's national identity, sovereignty or territorial integrity.

Continuity and change

Thus, taking an interest in the open border regime, the BP Koirala India-Nepal Foundation supported a field-based study of the open border in 2012-13. The Report deals with a variety of aspects, such as benefits and flaws; border management; encroachment controversy; use and misuse of the open border; No Man's Land; human and drug trafficking; security/insecurity; smuggling and the role of state agencies of both countries; water logging due to dams and barrages; and the use of the border for mutual benefits in education, health, livelihood and other socio-cultural relations.

The open border arrangement has been marked by both continuity and change. Its characteristics and compelling reasons give it a permanent feature but emergent trends and imperatives also make it change. Culturally, historically, economically and practically, the open border has been beneficial for both peoples. However, continuity also needs to address the emerging complexity and the problems that arise from time to time. Taking these aspects into account, the two governments have taken steps to streamline the open border. The deployment of the Seema Surakshya Bal (SSB) by India along the entire Indo-Nepal border, the border duties given to the Armed Police Force (APF) by Nepal and the creation of Coordinating Committees that meet when the need arises have considerably improved the regulation problem.

But it has been felt that these coordination committees should meet regularly to both generate trust and cooperation as well as to address the immediate problems that can arise in the field. India's SSB has six principal duties—stop smuggling, the movement of contraband goods and import/export without clearing custom duties; peace keeping and maintenance of internal security; control of criminals using the open border; security of custom and border areas, border pillars; prevent human trafficking; prevent transaction of arms and ammunition and fake currencies. SSB posts are placed along less than 4km intervals in order to enhance their role in regulating the border.

Nepal's APF is less equipped due to a lack of resources, both material and human; hence, skeleton check posts exist only in the Tarai. Our study finds that by and large, there has been a cooperative spirit between the SSB and APF, who meet from time to time to resolve immediate problems. It should be understood that Nepal-India relations are not conducted only through formal mechanisms and practices. Informal cooperation and coordination between security agencies of the two countries has tackled some immediate security and criminal-related problems. Sometimes, such operations go beyond the established norms of cooperation and trigger controversies but efforts should be made to respect each others' sensitivity while conducting such operations.

Delegate authority

Yet, local authorities and security agencies have no mandate to fix new pillars or maintain No Man's Land. The two governments could delegate authority to place new pillars and demarcate the boundary once they decide to allocate such duties to local level authorities.

First, the border should be demarcated on the basis of longitude-latitude so that missing areas can be easily located. When rivers change their course during the monsoon or pillars get lost, such an approach would be useful. The Indo-Nepal border also has a human dimension as children, women and others work as carriers of goods for smugglers. Community-level awareness, the improvement of economic conditions and educational opportunities for children living near the border could help minimise the problem.

Border regulation has become much more streamlined in recent years. But some territories—such as Susta, Pashupatinagar in Ilam and Kalapani—continue to remain disputed. A prompt and cooperative attitude by both sides can resolve these issues. A scientific map prepared by the two sides and a willingness to act on the basis of such a map can settle the vexing problem. A taskforce can be created to finalise the map. Indian Prime Minister Narendra Modi's visit to Nepal could be used as an opportunity to take such a decision and reach an agreement within a timeframe.
 
We should also realise that an international open border will not be completely free of occasional problems, as some pinpricks may arise from time to time without impairing the basics of the existing relationship. But vigilance on both sides and the delegation of authority to the local level can manage such recurring problems.  

Baral was Coordinator of the BPKF Open Border Study Team and is a former Nepali Ambassador to India.

source: \url{https://kathmandupost.com/opinion/2014/06/24/order-on-the-border}
