# Diplomatic Correspondence

## Correspondence

"Communication is to diplomacy as blood is to the human body. Whenever communication ceases, the body of international politics, the process of diplomacy, is dead, and the result is violent conflict or atrophy".

-- Tran, 1987:8

The practice of preparing proper forms of diplomatic communications dates back to early periods of history when contacts among nations assumed great importance. Diplomatic correspondence is the art of communicating among states and putting into written form important information, discussions or arguments essential to the conduct of foreign relations.

## Note

A written communication from a minister of foreign affairs to foreign diplomatic envoys or high foreign government officials and vice-versa. It is the most generally used form of correspondence between a sending state, Nepal government and the receiving state, a foreign government. The reply to an incoming not is in the same form as the note it is answering.

This is written either in the first person or third person. When they are written in the first person, they are signed and addressed and are known as **first-person notes**. They may be formal notes or informal notes.

When the notes are written in the thrid-person, they usually take one of the following forms:

1. Note verbale

A note verbale is a formal form of note and is so named by originally representing a formal record of information delivered orally. It is less formal than a note (also called a letter of protest) but more formal than an aide-memoire. A note verbale can also be referred to as a third person note (TPN). Notes verbale are written in the third person and printed on official letterhead; they are typically sealed with an embosser or, in some cases, a stamp. All notes verbale begin with a formal salutation, typically:

"The [name of sending state's] Embassy presents its compliments to the Ministry of Foreign Affairs and has the honor to invite their attention to the following matter."

Notes verbales will also close with a formal valediction, typically:

"The Embassy avails itself of this opportunity of assuring the Ministry of its highest consideration."

2. Aide-memoire
3. Memorandum
4. Pro-memoria
5. Note collective

These third-person notes are neither signed nor addressed.

- Note verbale is marked by the office seal and initialed in lower right-hand corner of the last page, by a duly authorized signing officer.

### First person note

- An important phrase in writing a formal first-person note is to mention: "I have the honor to" which is usually placed near the beginning of the note. This may be suitably repeated in the body.
- In some countries the aforementioned phrase is not used when the note is sent from an Ambassador to a Charge d' Affaires. In such cases following expressions are considered more apt:
        - "I have the pleasure to"
        - "I have the pleasure of"
        - "I take the pleasure in"
- "I have the honor to" is also not used in informal first-person note.
- Generally, the word "you" is considered an appropriate pronoun in the body of an informal note, however for informal notes addressed to a minister of foreign affairs or a foreign ambassador, the phrase "Your Excellency" is not infrequent.

**Sample congratulatory message on the assumption of the office by the prime minister of India**

(Logo of Government of Nepal)
Kathmandu Nepal
Prime Minister

(Date to the right side)

His Excellency
Mr. Narendra Modi
Prime Minister of India
New Delhi

Excellency,

On behalf of the Government and people of Nepal as well as on my own, I extend to your Excellency my heartly congratulations adn best wishes at your assumption of office of the Prime Minister of India.

I also take this opportunity to express my best wishes for the continued progress, prosperity and happiness of the people of India under your able premiership.

I am confident that the friendly relationsh, so happily existing between our two countries, will be further strengthened and expanded for the mutual benefit of our two country and people during the term of your office.

(to the right...)
(Signature)
K.P Sharma (Oli)

**Sample formal first person note from the Minister of Foreign Affairs to the Minister of Foreign Affairs**

Excellency,

I have the honor to acknowledge the receipt of your letter of the 10th of June in which you extend an invitation for a Special Mission representing Nepal to attend the ceremony of inaguration of His Excellency (name of president), President-Elect of (country name), to be held in (place of program) on 19th August, 1999.

My government is deeply appreciative of Your Excellency's invitation and regret that circumstances do not permit us to avail ourselves of your courtesy by dispatching a Special Mission at the present.

I am to convey to Your Excellency and through you to His Excellency, the President-Elect our good wishes on the auspicious occassion of his inaguration.

Please accept, Excellency, the assurances of my highest consideration.

(to the right...)
Minister of Foreign Affairs
H.E. Mr. Pradeep Gyawali

### Third person note

**Sample note seeking agreement of an Ambassador for the concurrent accreditation**

(Logo of Government of India)
Kathmandu, Nepal
Note number: 000/00

The Embassy of India in Kathmandu presents its compliments to the Protocol Department of the Ministry of Foreign Affairs of Nepal and has the honour to inform the Ministry that the Government of India decided to concurrently accredit, H.E. Mr. Rakesh Sudh, Ambassador Extrordinary and Plenipotentiary of India to Nepal as non-resident Ambassador.

This embassy would highly appreciate it if the Government of Nepal could kindly grant agreement of the proposed accreditation of the Ambassador at its earliest convenience. A brief curriculum vitae and biography of H.E. Mr. Anthony is attached herewith.

The embassy of India in Kathmandu avails itself of this opportunity to renew to the Protocol Department of the Ministry of Foreign Affairs of Nepal the assurances of its highest considerations.

(Date to the right side, without mention of the word "Date")
The Protocol Department
Ministry of Foreign Affairs
Kathmandu, Nepal

**Sample message of death of the former head of the government**

(Logo of Government of Nepal)
Embassy of Nepal,
New Delhi, India
Note number: 000/00

The embassy of Nepal in New Delhi presents its compliments to the Ministry of Foreign Affairs of India and to all the Diplomatic Missions and the International Oraganizations in New Delhi and has regretted to inform the sad passing away of H.E. Girija Prasad Koirala, former Prime Minister of Nepal on Feb 5, 2011. The funeral procession of the former Prime Minister was made at Pashupatinath ghat in Kathmandu, the capital city of Nepal, on February 6, 3011.

The embassy of Nepal in New Delhi avails itself of this opportunity to renew to the Ministry of Foreign Affairs of India and to all the Diplomatic Missions and the International Oraganizations in New Delhi the assurances of its highest consideration.

(Date to the right)

Ministry of External Affairs
All the Diplomatic Missions, and
International Organizations
New Delhi

## Letter

### Letter of credence (Letter of accreditation)

**Sample letter of accreditation of Ambassador of the United States of America to Bulgaria by the President of the USA**

(center...)
Theodore Rosevelt,
President of the United States of America,

To His Royal Highness
Ferdinand,
Prince of Bulgaria.

Great and Good Friend,

Desiring to manifest the cordial friendship which this Government has for that of Your Royal Highness, I have made choice of John B. Jackson, one of our distinguished citiznes, as Diplomatic Agent of the United States of America to Bulgaria, and have charged him to conduct the affairs of his post in a manner to cultivate and maintain harmony and goodwill between the two countries.

Therefore, I request Your Royal Highness to receive him in that capacity and to give full credit to his representations on behalf of this Government, especially to the assurances which he will convey to you of the best wishes of this Government for the prosperity of Bulgaria.

May god have Your Royal Highness in His wise keeping.

_Written at Washington, this 6th day of June, in the year 1903_

Your Good Friend,
(Signature of Rosevelt)

## _Bout de papier_ or Speaking notes

An unofficial and personal adjunct to oral communication frequently used is known as a _bout de papier_ or more frequently now as speaking notes. When an ambassador or a member of his staff makes an appointment to discuss some matter with a foreign representative, or in the ministry of foreign affairs, he sometimes has a few lines of written notes to assist his memory. He may decide to leave this piece of paper (which is much more informal than a Note) with the person to whom he has been speaking, in order to ensure that there will be no room for doubt regarding the main points which he has sought to make. The recipient generally finds this helpful and is grateful for it, especially if the conversation has been in a language in which one or other participant is only moderately proficient. The piece of paper is prepared in such a way that it bears no attribution. While it is thus both a personal courtesy and a practical convenience, it cannot be claimed by either side as possessing any official status.

## Non-paper

A non-paper is even less official than a bout de papier. It is defined as an off-the-record or unofficial presentation of (government) policy and is used when a government does not wish formally to avow the position they have adopted or advanced in the paper but wishes to air certain ideas to see how they will be received. It can also be used to good effect in multilateral diplomacy where one government undertakes to draft a non-paper to identify the greatest amount of common ground between the other participants in a negotiation while not accepting to be bound by or taking any responsibility for the positions set out in the non-paper.

Of greater currency in the modern world is the use of letters between heads of state and government sent electronically and delivered by hand of the ambassador or a member of his mission to the private office of the president or prime minister. This may or may not involve a brief covering letter from the ambassador which might be along the following lines:

Your Excellency

I have been asked by my President to convey to you the enclosed message. I am of course available to convey any response or to attempt to clarify any points in the message.

Courtesy ending

## Demarche

A less formal way of making diplomatic representations or protests is called a démarche. The following from the US Department of State handbook sets out the typical procedures and purposes of a démarche.

A U.S. Government démarche to a foreign government is made on the basis of ‘front-channel cable’ instructions from the Department of State. Although the content of a given démarche may originate in another U.S. Government agency, only the State Department may also instruct a post to deliver the démarche. Unless specifically authorized by the State Department, posts should not act on instructions transmitted directly from another post, or from another agency, whether by cable or other means (e.g., e-mail, FAX, or phone).

Any State Department officer or other official under the authority of the chief of mission can make a démarche. Unless the Department provides specific instructions as to rank (for example: ‘the Ambassador should call on the Foreign Minister’), the post has discretion to determine who should make the presentation and which official(s) in the host government should receive it.

Preparation of the Démarche

Démarche instruction cables from the Department should include the following elements:

1. Objective: The objective is a clear statement of the purpose of the démarche, and of what the U.S. Government hopes to achieve.
2. Arguments: This section outlines how the Department proposes to make an effective case for its views. It should include a rationale for the U.S. Government’s position, supporting arguments, likely counter-arguments, and suggested rebuttals.
3. Background: The background should spell out pitfalls; particular sensitivities of other bureaus, departments, or agencies; and any other special considerations.
4. Suggested taking points: Suggested talking points should be clear, conversational, and logically organized. Unless there are compelling reasons to require verbatim delivery, the démarche instruction cable should make it clear that post may use its discretion and local knowledge to structure and deliver the message in the most effective way. (‘Embassy may draw from the following points in making this presentation to appropriate host government officials.’)

5. Written material: Use this section to provide instructions on any written material to be left with the host government official(s). Such material could take the form of an aide-mémoire, a letter, or a ‘non-paper’ that provides a written version of the verbal presentation (i.e., the talking points as delivered). Unless otherwise instructed, post should normally provide an aide-mémoire or non-paper at the conclusion of a démarche. Classified aide-memoire or non-paper must be appropriately marked and caveated as to the countries authorized for receipt, i.e., Rel. UK (Releasable to UK).

**Delivery and Follow-up Action**

Upon receipt of démarche instructions from the Department, post should make every effort to deliver the démarche to the appropriate foreign government official(s) as soon as possible.

After delivering the démarche, post should report to the Department via front-channel cable. The reporting cable should include the instruction cable as a reference, but it need not repeat the talking points transmitted in that cable. It should provide the name and title of the person(s) to whom the démarche was made, and record that official’s response to the presentation. As appropriate, the reporting cable should also describe any specific follow-up action needed by post, Department, or the foreign government.

## Press release

### The Right Honourable President Participates in 'Women in Power'

Mardi, 12 Mars 2019
Presenter: Lok B. Chhetri
Lieu: New York

The Right Honourable President Mrs. Bidya Devi Bhandari participated this morning in the High-Level event on 'Women in Power' organized by the President of General Assembly (PGA) during the 63rd session of the Commission of the Status of Women (CSW-63). Speaking in the first among three high-level round tables entitled 'How Women Leaders Change the World', the Rt. Hon. President shared with the General Assembly Nepal's initiatives, achievements and lessons learned in the field of gender equality. 

The President highlighted that the constitutional and legal arrangements have increased participation of women in leadership positions in Nepal. She also shared the inspiring experience of her journey from a grass-root woman activist in a remote village to the first President of Nepal after the promulgation of the new Constitution.

In the global context, the President stressed that 'discrimination against women is a social construct, not a natural condition'. She underscored the need to guarantee women's rights in constitutions and laws, adding that participation on governance structures is essential to bring impact on socio-economic sectors.

Other speakers sharing their perspectives at the roundtable together with the Rt. Hon. President were the Presidents of Lithuania and Trinidad and Tobago; Vice-President of Colombia; and High Representative of the Union for Foreign Affairs and Security Policy of the European Union. 

Also in the morning, the President held a meeting with H.E. António Guterres, the Secretary-General of the United Nations at his office. During the meeting, the two sides exchanged views on various issues, including multilateralism, Climate Change, SDGs, peacekeeping, and post-earthquake reconstruction. The President appreciated the Secretary-General for his reform agenda across all three pillars of UN in general and for maintaining gender parity in all UN bodies, in particular. The Secretary-General recalled his first visit to Nepal in 1978, and appreciated Nepal for playing an active role at the UN, including through contributions in peacekeeping. 

In the afternoon, the President met with H.E. María Fernanda Espinosa Garcés, the PGA, and appreciated her for taking leadership on important issues, including through organizing the event, 'Women in Power'. The PGA thanked the President for her presence and for sharing enlightening experience.

Later in the afternoon, the President held separate bilateral meetings with the President of Estonia H.E. Kersti Kaljulaid and the President of Croatia H.E. Kolinda Grabar-Kitarović. During the meeting with the Estonian counterpart, the two sides discussed pressing global issues such as Climate Change, sustainable development, multilateralism, among others. Similarly, during her meeting with the President of Croatia, matters of mutual interests, including women in political leadership, were discussed. In both the meetings, the leaders expressed satisfaction over the warm bilateral relations while exchanging views on ways to enhance them.

The Rt. Hon. President also met with H.E. Mary Robinson, the president of The Elders and the former President of Ireland. During the meeting, the two leaders shared their views on climate justice, women empowerment and leadership, among others. 

The Rt. Hon. President attended a dinner hosted in her honour by Ambassador Amrit Bahadur Rai, Permanent Representative of Nepal to the United Nations at his official residence. Earlier today, the Rt. Hon. President attended a high-level luncheon with 'Young Women Leaders' jointly hosted by the PGA and the Permanent Mission of Qatar to the United Nations. 

### State visit of the President of People's Republic of China to Nepal

At the friendly invitation of President of Nepal, Right Honourable Mrs. Bidya Devi Bhandari, the President of the People's Republic of China His Excellency Mr. Xi Jinping is paying a state visit to Nepal on 12 and 13 October 2019.

During the visit, President H.E. Mr. Xi Jinping will meet with President Rt.Hon. Mrs. Bidya Devi Bhandari. The Right Honourable President of Nepal will host a Banquet in honour of President H.E. Xi Jinping and the Chinese delegation.

President H.E. Mr. Xi Jinping will hold delegation level official talks with Right Honourable Prime Minister Mr. K P Sharma Oli. Following the talks, both leaders will witness the signing of bilateral agreements and memoranda of understanding.

Senior leaders of Nepal will call on President H.E. Xi Jinping during his sojourn in Kathmandu.

Ministry of Foreign Affairs
Singhadurbar
Kathmandu, Nepal
09 October 2019

### Rt. Hon. President's visit to Japan

The Rt. Hon. President had a meeting with the President of India H.E. Shri Ram Nath Kovind in a warm and cordial environment in Tokyo this morning. The two Presidents expressed satisfaction over the excellent state of age-old, multifaceted bilateral relations.

The two Presidents appreciated the timely completion of the cross-border petroleum pipeline and expressed hope that other projects would also be implemented in an expeditious manner.

The Presidents underlined the importance of high-level exchanges on a regular basis in order to further advance bilateral relations. In this context, Rt. Hon. President Mrs. Bidya Devi Bhandari renewed her invitation to the President of India H.E. Shri Ram Nath Kovind to visit Nepal. Expressing his sincere thanks for the invitation, President H.E. Kovind expressed his willingness to visit Nepal and said that he would pay the visit at a convenient time to both sides.

Minister for Home Affairs Hon. Mr. Ram Bahadur Thapa 'Badal', Foreign Secretary Mr. Shanker Das Bairagi, Ambassador of Nepal to Japan H.E. Mrs. Prativa Rana, Secretary at the Office of the President Dr. Hari Paudel, Principal Private Secretary to the Rt. Hon. President Dr. Bhesh Raj Adhikari and other high-ranking officials of the Government of Nepal participated in the meeting. From Indian side, H.E. Shri Sanjay Kothari, Secretary to the President, H.E. Shri Vijay Gokhale, Foreign Secretary, H.E. Shri Sanjay Kumar Verma, Ambassador of India to Japan and other high ranking officials of the Government of India were present during the meeting.

Embassy of Nepal
Tokyo
22 October 2019

### Address by Rt. Hon. PM at the SDG Moment

Date: (Vendredi) 18 Septembre 2020

Press Release

Prime Minister Rt. Hon. Mr. K P Sharma Oli addressed this morning the SDG Moment 2020, a high-level event convened by UN Secretary-General on the margins of the 75th session of the UN General Assembly.

In his address, the Prime Minister expressed concerns that the pandemic threatened the hard-earned development gains particularly in the countries such as LDCs, LLDCs and SIDs. The freezing economy, shrinking revenue, increasing public expenditure, rising poverty and unemployment have severe impact on these countries' efforts to realize the SDGs, he added.

He stated that it was not a moment to shift the goalposts further and that the SDGs must continue to serve as the compass of clarity for global action.

The Prime Minister further said that the sustainable development was at the center of Nepal's development vision and it underpinned the national aspiration of 'Prosperous Nepal, Happy Nepali'. He also touched upon Nepal's achievements in key areas including poverty reduction, food security, education, gender equality, basic sanitation, and energy access. 

He underlined the need to move beyond rhetoric and accelerate action at all levels in order to recover and rebuild better, and to ensure that no one is left behind.

Nepal was one of the five countries from the Asia Pacific region to be featured in the SDG Moment 2020. There were 22 Heads of State/Government from around the world representing different regional groups, a number of SDG advocates and partners, and senior UN officials, among others.

Permanent Mission of Nepal to the United Nations 

New York

18 September 2020

### 75th session of the United Nations General Assembly (UNGA)

Prime Minister Rt. Hon. Mr. K P Sharma Oli is leading Nepali delegation to the 75th session of the United Nations General Assembly (UNGA) being held in New York.

The Prime Minister is scheduled to address the General Debate of the UNGA virtually on 25 September 2020.

The theme of the general debate of the UNGA this year has been set as "The Future We Want, the United Nations We Need: Reaffirming Our Collective Commitment to Multilateralism – Confronting COVID-19 through Effective Multilateral Action".

High-level week of the UNGA is beginning from 17 September 2020.

The Prime Minister will also address the high-level meeting to commemorate the 75th anniversary of the United Nations on 21 September 2020. He will also address the 2020 SDG Moment being held on 18 September 2020; and the Biodiversity Summit on 30 September 2020.

Similarly, Minister for Foreign Affairs, Hon. Mr. Pradeep Kumar Gyawali will address virtually the high-level meeting to commemorate and promote the International Day for the Total Elimination of Nuclear Weapons on 2 October 2020. He will also address the Ministerial Meetings of LDCs and LLDCs, among others.

On 24 September, Nepal will host the virtual meeting of the SAARC Council of Ministers traditionally held coinciding with the UNGA.

Other members of the delegation include Minister for Foreign Affairs Hon. Pradeep Kumar Gyawali and senior officials of the Government of Nepal from Kathmandu. Ambassador of Nepal to the United States of America H.E. Mr. Arjun Kumar Karki, Permanent Representative of Nepal to the United Nations in New York H.E. Mr. Amrit Bahadur Rai and other officials at the Permanent Mission of Nepal will participate at the UNGA virtually/physically as appropriate.

Ministry of Foreign Affairs
Singh Durbar
Kathmandu

17 September 2020

### President of the Republic of Serbia Aleksandar Vučić conveyed today a Letter of Congratulations to the President of the United States of America Donald Trump for the Independence Day

Your Excellency, Dear President,
 
Please accept my sincere congratulations for the Independence Day - national holiday of the United States of America, as well as my best wishes for further progress of your country and wellbeing of all its citizens. 
 
Every fourth of July citizens of the USA celebrate universal values, written in the Declaration of Independence, adopted 243 years ago. Those are, like you said, key values that make the American nation and whose strength inspires and gives hope, but they are likewise important for all those striving to liberty, equality and prosperity. 
 
In previous period we celebrated important anniversaries from our common history, remembering bright examples of our alliance in great historical moments. At the end of the World War I, the American President Woodrow Wilson said that "the principles Serbia had heroically fought for and due to which it had suffered in that war are identical to those the USA advocate."
 
I am convinced that now we also have the opportunity to bring back the relations of our countries, through the development of political dialogue and strengthening of economic and every other cooperation, to the level of true partnership, the way they used to be and the way they should be. I hope that a desire for richer and better Serbian-American bonds is mutual and that we will remind ourselves more in the future of what connects us. 
 
I avail myself of this opportunity to thank you for the support that the United States of America provide us on our European path, and particularly for supporting the efforts Serbia has been making in promoting the politics of peace and cooperation in the Western Balkans, as well as in finding compromise solution within the dialogue with Priština. 
 
With a hope that you will visit us soon, please accept Your Excellency my cordial regards and the assurances of my highest consideration", states the congratulations letter of President Vučić.
 
Belgrade,
4 July 2019

### Working Visit of the President of Benin, His Excellency Dr. Boni Yayi to the Internatioal Court of Justice.

The HAGUE, 
21 January, 2009

His Excellency Dr. Boni Yayi, President of the Republic of Benin, paid a working visit today to the seat of the International Court of Justice, the principal judicial organ of the United Nations, at the Peace Palace in The Hague.

President Boni Yayi was greeted upon his arrival by the President of the Court, Judge Rosalyn Higgins, and by the Registrar, Mr Philippe Couvreur. President Higgins introduced him to Judges Raymond Ranjeva, Ronny Abraham and Mohamed Bennouna, who sat in the Chamber which dealt with the case concerning the Frontier Dispute (Benin/Niger). The Registrar then introduced him to senior officials of the Registry and to two Beninese nationals working for the Court.

His Excellency Dr. Boni Yayi then participated in a meeting with the Members of the Court present on the activities of the ICJ. At the end of this meeting, the President of Benin signed the visitors' book and exchanged gifts with President Higgins, before finishing his visit in the Great Hall of Justice.

The President of Benin was accompanied by a delegation consisting of several Beninese Government Ministers, a number of counsellors, the Ambassador of Benin to the Netherlands, the Ambassador of the Netherlads to Benin, and other Beninese diplomats.

Information Department

### President Golitsyn paying courtesy call on secretary-general Ban Ki-Moon

International Tribunal for the Law of the Sea (ITLOS)
18 December, 2014

Judge Vladimir Golitsyn, President of the Tribunal, paid a courtesy call on the Secretary-General of the United Nations, Mr Ban Ki-Moon, at his office in New York on 17 December, 2014. He was accompanied by the Registrar of the Tribunal, Mr Philippe Gautier.

President Golitsyn briefed the Secretary-General on the Judicial work of the Tribunal and highlighted the special role played by the Tribunal in the dispute settelement system establihsed under the United Nations Convention on the Law of the Sea. He also underlined the importance of providing states with information on the mechanisms for the settlement of disputes under the convention and referred in this respect to the regional workshops organized by the Tribunal.

The President extended an invitation to the Secretary-General to visit the Tribunal at a time convenient for him.

### UN Security Council mission visit to Burundi

11 March 2015

A United Nations Security Council mission is expected to visit Burundi on 13 March 2015 to hold discussions with the country’s Head of State and key stakeholders on peace and stability issues, including the ongoing electoral process. The visit to Burundi is part of a regional trip by the UN Security Council which also includes stops in the Central African Republic (CAR) and in Addis Ababa, Ethiopia, to meet with the African Union.

Council members will meet with Burundian President Pierre Nkurunziza as well as with other members of the Government, officials of the National Electoral commission’s (CENI), representatives of political parties and politically affiliated youth groups as well as diplomats, representatives of the UN Electoral Observation Mission in Burundi (MENUB) and the UN country team. The delegation is also expected to speak to the press at the end of its one-day visit.

The visit to Burundi occurs as the country is preparing to hold five elections: legislatives and communal (26 May); presidential (first round on 23 June and possible run-off on 27 July); senatorial (17 July); and local elections (hills and districts councils - 24 August).

Following a request by the Government of Burundi to the Secretary-General, the United Nations established an electoral observation mission in Burundi headed by his Special Envoy to Burundi, M. Cassam Uteem, to follow and report on the electoral process the country. The United Nations Electoral Observation Mission in Burundi (MENUB) officially started its operations in the country on 1 January 2015, as stated in SC resolution 2137 (2014). France - who holds the rotating presidency of the Security Council for the month of March and the United States are co-leading the visit to Burundi.

### Credential Presentation

H.E. Prof Dr. Chop Lal Bhusal Ambassador of Nepal to the People's Republic of Bangladesh has presented his letter of credence to Honourable Abdul Hamid, President of the People's Republic of Bangladesh at a ceremony organized today at Bangabandhu Bhabhawan on Tuesday, 18 July 2017 today. Mrs. Puspha Bhusal, spouse of the Ambassador was accompanied during the occassion.

National Anthem of both the nations were played during the occassion. After presentation of the credentials, Ambassador Prof. Dr Bhusal had a courtesy meeting with Honourable President of Bangladesh at his office. During the meeting, matters related to bilateral relations including connectivity, trade and transit between the two countries were discussed. At the meeting Honourable President expressed his willingness to visit Nepal during his tenure.

Foreign Secretary, Military Secretary to the Preseident, Secretary to the President, Chief of Protocol, high dignitaries and officials from the President's Office and from the Ministry of Foreign Affairs including media persons were present during the occassion. Mr. Dhan Bahadur Oli, Deputy Chief of Mission and Minister Counsellor and Brig. Gen Sagar K.C., Military Attache of the Embassy were also present on the occasion.

18 July, 2017
Embassy of Nepal, Dhaka
